[package]
edition = "2021"
name = "vorpal"
publish = false
version = "0.1.0"

[[bin]]
name = "vorpal"
path = "src/main.rs"

[dependencies]
anyhow = "1"
tokio = { features = ["rt-multi-thread"], version = "1" }
vorpal-sdk = "0.2.0-alpha"
