// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: archive/archive.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleClientStreamingCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "vorpal.archive";

export interface ArchivePullRequest {
  digest: string;
  namespace: string;
}

export interface ArchivePushRequest {
  data: Buffer;
  digest: string;
  namespace: string;
}

export interface ArchiveResponse {
}

export interface ArchivePullResponse {
  data: Buffer;
}

function createBaseArchivePullRequest(): ArchivePullRequest {
  return { digest: "", namespace: "" };
}

export const ArchivePullRequest: MessageFns<ArchivePullRequest> = {
  encode(message: ArchivePullRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.digest !== "") {
      writer.uint32(10).string(message.digest);
    }
    if (message.namespace !== "") {
      writer.uint32(18).string(message.namespace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchivePullRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchivePullRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchivePullRequest {
    return {
      digest: isSet(object.digest) ? globalThis.String(object.digest) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
    };
  },

  toJSON(message: ArchivePullRequest): unknown {
    const obj: any = {};
    if (message.digest !== "") {
      obj.digest = message.digest;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchivePullRequest>, I>>(base?: I): ArchivePullRequest {
    return ArchivePullRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchivePullRequest>, I>>(object: I): ArchivePullRequest {
    const message = createBaseArchivePullRequest();
    message.digest = object.digest ?? "";
    message.namespace = object.namespace ?? "";
    return message;
  },
};

function createBaseArchivePushRequest(): ArchivePushRequest {
  return { data: Buffer.alloc(0), digest: "", namespace: "" };
}

export const ArchivePushRequest: MessageFns<ArchivePushRequest> = {
  encode(message: ArchivePushRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    if (message.digest !== "") {
      writer.uint32(18).string(message.digest);
    }
    if (message.namespace !== "") {
      writer.uint32(26).string(message.namespace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchivePushRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchivePushRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchivePushRequest {
    return {
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
      digest: isSet(object.digest) ? globalThis.String(object.digest) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
    };
  },

  toJSON(message: ArchivePushRequest): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.digest !== "") {
      obj.digest = message.digest;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchivePushRequest>, I>>(base?: I): ArchivePushRequest {
    return ArchivePushRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchivePushRequest>, I>>(object: I): ArchivePushRequest {
    const message = createBaseArchivePushRequest();
    message.data = object.data ?? Buffer.alloc(0);
    message.digest = object.digest ?? "";
    message.namespace = object.namespace ?? "";
    return message;
  },
};

function createBaseArchiveResponse(): ArchiveResponse {
  return {};
}

export const ArchiveResponse: MessageFns<ArchiveResponse> = {
  encode(_: ArchiveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ArchiveResponse {
    return {};
  },

  toJSON(_: ArchiveResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveResponse>, I>>(base?: I): ArchiveResponse {
    return ArchiveResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveResponse>, I>>(_: I): ArchiveResponse {
    const message = createBaseArchiveResponse();
    return message;
  },
};

function createBaseArchivePullResponse(): ArchivePullResponse {
  return { data: Buffer.alloc(0) };
}

export const ArchivePullResponse: MessageFns<ArchivePullResponse> = {
  encode(message: ArchivePullResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchivePullResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchivePullResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchivePullResponse {
    return { data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0) };
  },

  toJSON(message: ArchivePullResponse): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchivePullResponse>, I>>(base?: I): ArchivePullResponse {
    return ArchivePullResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchivePullResponse>, I>>(object: I): ArchivePullResponse {
    const message = createBaseArchivePullResponse();
    message.data = object.data ?? Buffer.alloc(0);
    return message;
  },
};

export type ArchiveServiceService = typeof ArchiveServiceService;
export const ArchiveServiceService = {
  check: {
    path: "/vorpal.archive.ArchiveService/Check" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchivePullRequest): Buffer => Buffer.from(ArchivePullRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchivePullRequest => ArchivePullRequest.decode(value),
    responseSerialize: (value: ArchiveResponse): Buffer => Buffer.from(ArchiveResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveResponse => ArchiveResponse.decode(value),
  },
  pull: {
    path: "/vorpal.archive.ArchiveService/Pull" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: ArchivePullRequest): Buffer => Buffer.from(ArchivePullRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchivePullRequest => ArchivePullRequest.decode(value),
    responseSerialize: (value: ArchivePullResponse): Buffer => Buffer.from(ArchivePullResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchivePullResponse => ArchivePullResponse.decode(value),
  },
  push: {
    path: "/vorpal.archive.ArchiveService/Push" as const,
    requestStream: true as const,
    responseStream: false as const,
    requestSerialize: (value: ArchivePushRequest): Buffer => Buffer.from(ArchivePushRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchivePushRequest => ArchivePushRequest.decode(value),
    responseSerialize: (value: ArchiveResponse): Buffer => Buffer.from(ArchiveResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveResponse => ArchiveResponse.decode(value),
  },
} as const;

export interface ArchiveServiceServer extends UntypedServiceImplementation {
  check: handleUnaryCall<ArchivePullRequest, ArchiveResponse>;
  pull: handleServerStreamingCall<ArchivePullRequest, ArchivePullResponse>;
  push: handleClientStreamingCall<ArchivePushRequest, ArchiveResponse>;
}

export interface ArchiveServiceClient extends Client {
  check(
    request: ArchivePullRequest,
    callback: (error: ServiceError | null, response: ArchiveResponse) => void,
  ): ClientUnaryCall;
  check(
    request: ArchivePullRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveResponse) => void,
  ): ClientUnaryCall;
  check(
    request: ArchivePullRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveResponse) => void,
  ): ClientUnaryCall;
  pull(request: ArchivePullRequest, options?: Partial<CallOptions>): ClientReadableStream<ArchivePullResponse>;
  pull(
    request: ArchivePullRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ArchivePullResponse>;
  push(
    callback: (error: ServiceError | null, response: ArchiveResponse) => void,
  ): ClientWritableStream<ArchivePushRequest>;
  push(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveResponse) => void,
  ): ClientWritableStream<ArchivePushRequest>;
  push(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveResponse) => void,
  ): ClientWritableStream<ArchivePushRequest>;
  push(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveResponse) => void,
  ): ClientWritableStream<ArchivePushRequest>;
}

export const ArchiveServiceClient = makeGenericClientConstructor(
  ArchiveServiceService,
  "vorpal.archive.ArchiveService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ArchiveServiceClient;
  service: typeof ArchiveServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
