// Code generated by linux-vorpal-codegen. DO NOT EDIT.

import { ArtifactSystem } from "../../api/artifact/artifact.js";
import { Artifact } from "../../artifact.js";
import { bwrap } from "../step.js";
import { LinuxDebian } from "../linux_debian.js";
import type { ConfigContext } from "../../context.js";
import {
	setup,
	stage01,
	stage02,
	stage03,
	stage04,
	stage05,
} from "./scripts.js";
import {
	sourceCurl,
	sourceCurlCacert,
	sourceFile,
	sourceGnu,
	sourceGnuGcc,
	sourceGnuGlibcPatch,
	sourceGnuXz,
	sourceLibidn2,
	sourceLibpsl,
	sourceLinux,
	sourceNcurses,
	sourceOpenssl,
	sourcePerl,
	sourcePython,
	sourceUnzip,
	sourceUnzipPatchFixes,
	sourceUnzipPatchGcc14,
	sourceUtilLinux,
	sourceXz,
	sourceZlib,
} from "./source.js";

export async function linuxVorpal(ctx: ConfigContext): Promise<string> {
  const bashVersion = "5.3";
  const binutilsVersion = "2.45";
  const bisonVersion = "3.8.2";
  const coreutilsVersion = "9.7";
  const curlVersion = "8.15.0";
  const diffutilsVersion = "3.12";
  const fileVersion = "5.46";
  const findutilsVersion = "4.10.0";
  const gawkVersion = "5.3.2";
  const gccVersion = "15.2.0";
  const gettextVersion = "0.26";
  const glibcVersion = "2.42";
  const gmpVersion = "6.3.0";
  const grepVersion = "3.12";
  const gzipVersion = "1.14";
  const libidn2Version = "2.3.8";
  const libpslVersion = "0.21.5";
  const libunistringVersion = "1.3";
  const linuxVersion = "6.16.1";
  const m4Version = "1.4.20";
  const makeVersion = "4.4.1";
  const mpcVersion = "1.3.1";
  const mpfrVersion = "4.2.2";
  const ncursesVersion = "6.5-20250809";
  const opensslVersion = "3.5.2";
  const patchVersion = "2.8";
  const perlVersion = "5.42.0";
  const pythonVersion = "3.13.7";
  const sedVersion = "4.9";
  const tarVersion = "1.35";
  const texinfoVersion = "7.2";
  const unzipVersion = "6.0";
  const utilLinuxVersion = "2.41.1";
  const xzVersion = "5.8.1";
  const zlibVersion = "1.3.1";

  const bash = sourceGnu("bash", bashVersion);
  const binutils = sourceGnu("binutils", binutilsVersion);
  const bison = sourceGnu("bison", bisonVersion);
  const coreutils = sourceGnu("coreutils", coreutilsVersion);
  const curl = sourceCurl(curlVersion);
  const curlCacert = sourceCurlCacert();
  const diffutils = sourceGnuXz("diffutils", diffutilsVersion);
  const file = sourceFile(fileVersion);
  const findutils = sourceGnuXz("findutils", findutilsVersion);
  const gawk = sourceGnu("gawk", gawkVersion);
  const gcc = sourceGnuGcc(gccVersion);
  const gettext = sourceGnu("gettext", gettextVersion);
  const glibc = sourceGnu("glibc", glibcVersion);
  const glibcPatch = sourceGnuGlibcPatch(glibcVersion);
  const gmp = sourceGnu("gmp", gmpVersion);
  const grep = sourceGnu("grep", grepVersion);
  const gzip = sourceGnu("gzip", gzipVersion);
  const libidn2 = sourceLibidn2(libidn2Version);
  const libpsl = sourceLibpsl(libpslVersion);
  const libunistring = sourceGnu("libunistring", libunistringVersion);
  const linux = sourceLinux(linuxVersion);
  const m4 = sourceGnu("m4", m4Version);
  const makeSrc = sourceGnu("make", makeVersion);
  const mpc = sourceGnu("mpc", mpcVersion);
  const mpfr = sourceGnuXz("mpfr", mpfrVersion);
  const ncurses = sourceNcurses(ncursesVersion);
  const openssl = sourceOpenssl(opensslVersion);
  const patch = sourceGnu("patch", patchVersion);
  const perl = sourcePerl(perlVersion);
  const python = sourcePython(pythonVersion);
  const sed = sourceGnu("sed", sedVersion);
  const tar = sourceGnu("tar", tarVersion);
  const texinfo = sourceGnu("texinfo", texinfoVersion);
  const unzip = sourceUnzip(unzipVersion);
  const unzipPatchFixes = sourceUnzipPatchFixes("6.0");
  const unzipPatchGcc14 = sourceUnzipPatchGcc14("6.0");
  const utilLinux = sourceUtilLinux(utilLinuxVersion);
  const xz = sourceXz(xzVersion);
  const zlib = sourceZlib(zlibVersion);

  const stepEnvironments = ["PATH=/usr/bin:/usr/sbin"];

  const stepRootfs = await new LinuxDebian().build(ctx);

  const stepSetupScript = setup(
    binutilsVersion,
    gawkVersion,
    gccVersion,
    glibcVersion,
    gmpVersion,
    mpcVersion,
    mpfrVersion,
    ncursesVersion,
  );

  const stepStage01Script = stage01(
    binutilsVersion,
    gccVersion,
    glibcVersion,
    linuxVersion,
  );

  const stepStage02Script = stage02(
    bashVersion,
    binutilsVersion,
    coreutilsVersion,
    diffutilsVersion,
    fileVersion,
    findutilsVersion,
    gawkVersion,
    gccVersion,
    grepVersion,
    gzipVersion,
    m4Version,
    makeVersion,
    ncursesVersion,
    patchVersion,
    sedVersion,
    tarVersion,
    xzVersion,
  );

  const stepStage03Script = stage03(
    bisonVersion,
    gettextVersion,
    perlVersion,
    pythonVersion,
    texinfoVersion,
    utilLinuxVersion,
  );

  const stepStage04Script = stage04(
    binutilsVersion,
    gccVersion,
    glibcVersion,
    opensslVersion,
    zlibVersion,
  );

  const stepStage05Script = stage05(
    curlVersion,
    libidn2Version,
    libpslVersion,
    libunistringVersion,
    unzipVersion,
  );

  const bwrapArguments = [
	// mount bin
	"--bind",
	"$VORPAL_OUTPUT/bin",
	"/bin",
	// mount etc
	"--bind",
	"$VORPAL_OUTPUT/etc",
	"/etc",
	// mount lib
	"--bind",
	"$VORPAL_OUTPUT/lib",
	"/lib",
	// mount lib64 (if exists)
	"--bind-try",
	"$VORPAL_OUTPUT/lib64",
	"/lib64",
	// mount sbin
	"--bind",
	"$VORPAL_OUTPUT/sbin",
	"/sbin",
	// mount usr
	"--bind",
	"$VORPAL_OUTPUT/usr",
	"/usr",
	// mount current directory
	"--bind",
	"$VORPAL_WORKSPACE",
	"$VORPAL_WORKSPACE",
	// change directory
	"--chdir",
	"$VORPAL_WORKSPACE",
	// set group id
	"--gid",
	"0",
	// set user id
	"--uid",
	"0",
];

  const systems = [
	ArtifactSystem.AARCH64_LINUX,
	ArtifactSystem.X8664_LINUX,
];

  const steps = [
    await bwrap(
		[],
		[],
		[...stepEnvironments],
		stepRootfs,
		[],
		stepSetupScript,
	),
    await bwrap(
		[],
		[],
		[...stepEnvironments],
		stepRootfs,
		[],
		stepStage01Script,
	),
    await bwrap(
		[],
		[],
		[...stepEnvironments],
		stepRootfs,
		[],
		stepStage02Script,
	),
    await bwrap(
		[...bwrapArguments, "--bind", "$VORPAL_OUTPUT/tools", "/tools"],
		[],
		[...stepEnvironments],
		null,
		[],
		stepStage03Script,
	),
    await bwrap(
		[],
		[],
		[...stepEnvironments],
		stepRootfs,
		[],
		"rm -rf $VORPAL_OUTPUT/tools",
	),
    await bwrap(
		bwrapArguments,
		[],
		[...stepEnvironments],
		null,
		[],
		stepStage04Script,
	),
    await bwrap(
		bwrapArguments,
		[],
		[...stepEnvironments],
		null,
		[],
		stepStage05Script,
	),
  ];

  const sources = [
    bash,
    binutils,
    bison,
    coreutils,
    curl,
    curlCacert,
    diffutils,
    file,
    findutils,
    gawk,
    gcc,
    gettext,
    glibc,
    glibcPatch,
    gmp,
    grep,
    gzip,
    libidn2,
    libpsl,
    libunistring,
    linux,
    m4,
    makeSrc,
    mpc,
    mpfr,
    ncurses,
    openssl,
    patch,
    perl,
    python,
    sed,
    tar,
    texinfo,
    unzip,
    unzipPatchFixes,
    unzipPatchGcc14,
    utilLinux,
    xz,
    zlib,
  ];

  const name = "linux-vorpal";

	return new Artifact(name, steps, systems)
		.withAliases([`${name}:latest`])
		.withSources(sources)
		.build(ctx);
}
