// Code generated by linux-vorpal-codegen. DO NOT EDIT.

export { setup } from "./script_setup.js";
export { stage01 } from "./script_stage_01.js";
export { stage02 } from "./script_stage_02.js";
export { stage03 } from "./script_stage_03.js";
export { stage04 } from "./script_stage_04.js";
export { stage05 } from "./script_stage_05.js";
