FROM docker.io/library/debian:12.6-slim@sha256:f528891ab1aa484bf7233dbcc84f3c806c3e427571d75510a9d74bb5ec535b33

RUN apt-get update && apt-get install -y \
    # autoconf \
    # automake \
    # binutils \
    # bison \
    # byacc \
    # coreutils \
    # dpkg-dev \
    # file \
    # g++ \
    # gawk \
    # help2man \
    # libc6-dev \
    # libssl-dev \
    # libtool \
    # m4 \
    # make \
    # perl \
    # rsync \
    # texinfo \
    ca-certificates \
    gcc \
    libssl-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
