FROM docker.io/library/rust:1.80.0-slim@sha256:37e6f90f98b3afd15c2526d7abb257a1f4cb7d49808fe3729d9d62020b07b544

RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "aarch64" ]; then \
    ARCH="arm64"; \
    fi && \
    echo "Architecture set to $ARCH" && \
    apt-get update \
    && apt-get install --no-install-recommends --yes curl \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install --no-install-recommends --yes \
    docker-buildx-plugin \
    docker-ce-cli \
    docker-compose-plugin \
    libssl-dev \
    pkg-config \
    protobuf-compiler \
    && curl -fsSL https://github.com/tweag/nickel/releases/download/1.7.0/nickel-$ARCH-linux -o /usr/local/bin/nickel \
    && chmod +x /usr/local/bin/nickel \
    && curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin \
    && rustup component add clippy rust-analyzer rust-src rustfmt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
