FROM docker.io/library/debian:12.6-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d

ENV CARGO_HOME=/usr/local/cargo \
    RUSTUP_HOME=/usr/local/rustup \
    PATH=/usr/local/cargo/bin:$PATH

COPY script /usr/local/bin

RUN install-base \
    && install-docker \
    && install-just \
    && install-nickel \
    && install-nodejs \
    && install-rust \
    && install-clean
