// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v4.25.4
// source: worker/worker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type handleServerStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Artifact } from "../artifact/artifact.js";

export const protobufPackage = "vorpal.worker";

export interface BuildArtifactRequest {
  artifact_aliases: string[];
  artifact_namespace: string;
  registry: string;
  artifact?: Artifact | undefined;
}

export interface BuildArtifactResponse {
  output: string;
}

function createBaseBuildArtifactRequest(): BuildArtifactRequest {
  return { artifact_aliases: [], artifact_namespace: "", registry: "", artifact: undefined };
}

export const BuildArtifactRequest: MessageFns<BuildArtifactRequest> = {
  encode(message: BuildArtifactRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.artifact_aliases) {
      writer.uint32(10).string(v!);
    }
    if (message.artifact_namespace !== "") {
      writer.uint32(18).string(message.artifact_namespace);
    }
    if (message.registry !== "") {
      writer.uint32(34).string(message.registry);
    }
    if (message.artifact !== undefined) {
      Artifact.encode(message.artifact, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BuildArtifactRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBuildArtifactRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.artifact_aliases.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.artifact_namespace = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.registry = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.artifact = Artifact.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BuildArtifactRequest {
    return {
      artifact_aliases: globalThis.Array.isArray(object?.artifactAliases)
        ? object.artifactAliases.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.artifact_aliases)
        ? object.artifact_aliases.map((e: any) => globalThis.String(e))
        : [],
      artifact_namespace: isSet(object.artifactNamespace)
        ? globalThis.String(object.artifactNamespace)
        : isSet(object.artifact_namespace)
        ? globalThis.String(object.artifact_namespace)
        : "",
      registry: isSet(object.registry) ? globalThis.String(object.registry) : "",
      artifact: isSet(object.artifact) ? Artifact.fromJSON(object.artifact) : undefined,
    };
  },

  toJSON(message: BuildArtifactRequest): unknown {
    const obj: any = {};
    if (message.artifact_aliases?.length) {
      obj.artifactAliases = message.artifact_aliases;
    }
    if (message.artifact_namespace !== "") {
      obj.artifactNamespace = message.artifact_namespace;
    }
    if (message.registry !== "") {
      obj.registry = message.registry;
    }
    if (message.artifact !== undefined) {
      obj.artifact = Artifact.toJSON(message.artifact);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildArtifactRequest>, I>>(base?: I): BuildArtifactRequest {
    return BuildArtifactRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildArtifactRequest>, I>>(object: I): BuildArtifactRequest {
    const message = createBaseBuildArtifactRequest();
    message.artifact_aliases = object.artifact_aliases?.map((e) => e) || [];
    message.artifact_namespace = object.artifact_namespace ?? "";
    message.registry = object.registry ?? "";
    message.artifact = (object.artifact !== undefined && object.artifact !== null)
      ? Artifact.fromPartial(object.artifact)
      : undefined;
    return message;
  },
};

function createBaseBuildArtifactResponse(): BuildArtifactResponse {
  return { output: "" };
}

export const BuildArtifactResponse: MessageFns<BuildArtifactResponse> = {
  encode(message: BuildArtifactResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.output !== "") {
      writer.uint32(10).string(message.output);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BuildArtifactResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBuildArtifactResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.output = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BuildArtifactResponse {
    return { output: isSet(object.output) ? globalThis.String(object.output) : "" };
  },

  toJSON(message: BuildArtifactResponse): unknown {
    const obj: any = {};
    if (message.output !== "") {
      obj.output = message.output;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildArtifactResponse>, I>>(base?: I): BuildArtifactResponse {
    return BuildArtifactResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildArtifactResponse>, I>>(object: I): BuildArtifactResponse {
    const message = createBaseBuildArtifactResponse();
    message.output = object.output ?? "";
    return message;
  },
};

export type WorkerServiceService = typeof WorkerServiceService;
export const WorkerServiceService = {
  buildArtifact: {
    path: "/vorpal.worker.WorkerService/BuildArtifact",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: BuildArtifactRequest): Buffer => Buffer.from(BuildArtifactRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BuildArtifactRequest => BuildArtifactRequest.decode(value),
    responseSerialize: (value: BuildArtifactResponse): Buffer =>
      Buffer.from(BuildArtifactResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BuildArtifactResponse => BuildArtifactResponse.decode(value),
  },
} as const;

export interface WorkerServiceServer extends UntypedServiceImplementation {
  buildArtifact: handleServerStreamingCall<BuildArtifactRequest, BuildArtifactResponse>;
}

export interface WorkerServiceClient extends Client {
  buildArtifact(
    request: BuildArtifactRequest,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<BuildArtifactResponse>;
  buildArtifact(
    request: BuildArtifactRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<BuildArtifactResponse>;
}

export const WorkerServiceClient = makeGenericClientConstructor(
  WorkerServiceService,
  "vorpal.worker.WorkerService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): WorkerServiceClient;
  service: typeof WorkerServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
