// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: worker/worker.proto

package worker

import (
	artifact "github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/artifact"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildArtifactRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ArtifactAliases   []string               `protobuf:"bytes,1,rep,name=artifact_aliases,json=artifactAliases,proto3" json:"artifact_aliases,omitempty"`
	ArtifactNamespace string                 `protobuf:"bytes,2,opt,name=artifact_namespace,json=artifactNamespace,proto3" json:"artifact_namespace,omitempty"`
	Registry          string                 `protobuf:"bytes,4,opt,name=registry,proto3" json:"registry,omitempty"`
	Artifact          *artifact.Artifact     `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BuildArtifactRequest) Reset() {
	*x = BuildArtifactRequest{}
	mi := &file_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildArtifactRequest) ProtoMessage() {}

func (x *BuildArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildArtifactRequest.ProtoReflect.Descriptor instead.
func (*BuildArtifactRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *BuildArtifactRequest) GetArtifactAliases() []string {
	if x != nil {
		return x.ArtifactAliases
	}
	return nil
}

func (x *BuildArtifactRequest) GetArtifactNamespace() string {
	if x != nil {
		return x.ArtifactNamespace
	}
	return ""
}

func (x *BuildArtifactRequest) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *BuildArtifactRequest) GetArtifact() *artifact.Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type BuildArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildArtifactResponse) Reset() {
	*x = BuildArtifactResponse{}
	mi := &file_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildArtifactResponse) ProtoMessage() {}

func (x *BuildArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildArtifactResponse.ProtoReflect.Descriptor instead.
func (*BuildArtifactResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *BuildArtifactResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_worker_worker_proto protoreflect.FileDescriptor

const file_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x13worker/worker.proto\x12\rvorpal.worker\x1a\x17artifact/artifact.proto\"\xc3\x01\n" +
	"\x14BuildArtifactRequest\x12)\n" +
	"\x10artifact_aliases\x18\x01 \x03(\tR\x0fartifactAliases\x12-\n" +
	"\x12artifact_namespace\x18\x02 \x01(\tR\x11artifactNamespace\x12\x1a\n" +
	"\bregistry\x18\x04 \x01(\tR\bregistry\x125\n" +
	"\bartifact\x18\x03 \x01(\v2\x19.vorpal.artifact.ArtifactR\bartifact\"/\n" +
	"\x15BuildArtifactResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output2m\n" +
	"\rWorkerService\x12\\\n" +
	"\rBuildArtifact\x12#.vorpal.worker.BuildArtifactRequest\x1a$.vorpal.worker.BuildArtifactResponse0\x01B4Z2github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/workerb\x06proto3"

var (
	file_worker_worker_proto_rawDescOnce sync.Once
	file_worker_worker_proto_rawDescData []byte
)

func file_worker_worker_proto_rawDescGZIP() []byte {
	file_worker_worker_proto_rawDescOnce.Do(func() {
		file_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_worker_proto_rawDesc), len(file_worker_worker_proto_rawDesc)))
	})
	return file_worker_worker_proto_rawDescData
}

var file_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_worker_worker_proto_goTypes = []any{
	(*BuildArtifactRequest)(nil),  // 0: vorpal.worker.BuildArtifactRequest
	(*BuildArtifactResponse)(nil), // 1: vorpal.worker.BuildArtifactResponse
	(*artifact.Artifact)(nil),     // 2: vorpal.artifact.Artifact
}
var file_worker_worker_proto_depIdxs = []int32{
	2, // 0: vorpal.worker.BuildArtifactRequest.artifact:type_name -> vorpal.artifact.Artifact
	0, // 1: vorpal.worker.WorkerService.BuildArtifact:input_type -> vorpal.worker.BuildArtifactRequest
	1, // 2: vorpal.worker.WorkerService.BuildArtifact:output_type -> vorpal.worker.BuildArtifactResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_worker_worker_proto_init() }
func file_worker_worker_proto_init() {
	if File_worker_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_worker_proto_rawDesc), len(file_worker_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_worker_proto_goTypes,
		DependencyIndexes: file_worker_worker_proto_depIdxs,
		MessageInfos:      file_worker_worker_proto_msgTypes,
	}.Build()
	File_worker_worker_proto = out.File
	file_worker_worker_proto_goTypes = nil
	file_worker_worker_proto_depIdxs = nil
}
