name: 'setup-action'
author: 'ALT-F4-LLC'
description: 'Setup Vorpal in a pipeline.'

branding:
  color: 'red'
  icon: 'heart'

inputs:
  version:
    default: 0.1.0-rc.0
    description: Vorpal binary version to install.

runs:
  main: dist/index.js
  using: node20
