// Code generated by linux-vorpal-codegen. DO NOT EDIT.

package linux_vorpal

import (
	"fmt"
	"strings"

	api "github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/artifact"
	"github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/artifact"
)

func SourceCurl(version string) api.ArtifactSource {
	name := "curl"
	path := fmt.Sprintf("https://curl.se/download/%s-%s.tar.xz", name, version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceCurlCacert() api.ArtifactSource {
	name := "curl-cacert"
	path := "https://curl.se/ca/cacert.pem"

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceFile(version string) api.ArtifactSource {
	name := "file"
	path := fmt.Sprintf("https://astron.com/pub/file/file-%s.tar.gz", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceGnu(name string, version string) api.ArtifactSource {
	path := fmt.Sprintf("https://ftpmirror.gnu.org/gnu/%s/%s-%s.tar.gz", name, name, version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceGnuXz(name string, version string) api.ArtifactSource {
	path := fmt.Sprintf("https://ftpmirror.gnu.org/gnu/%s/%s-%s.tar.xz", name, name, version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceGnuGcc(version string) api.ArtifactSource {
	name := "gcc"
	path := fmt.Sprintf("https://ftpmirror.gnu.org/gnu/gcc/gcc-%s/gcc-%s.tar.xz", version, version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceGnuGlibcPatch(version string) api.ArtifactSource {
	name := "glibc-patch"
	path := fmt.Sprintf("https://www.linuxfromscratch.org/patches/lfs/12.4/glibc-%s-fhs-1.patch", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceLibidn2(version string) api.ArtifactSource {
	name := "libidn2"
	path := fmt.Sprintf("https://ftpmirror.gnu.org/gnu/libidn/libidn2-%s.tar.gz", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceLibpsl(version string) api.ArtifactSource {
	name := "libpsl"
	path := fmt.Sprintf("https://github.com/rockdaboot/libpsl/releases/download/%s/libpsl-%s.tar.gz", version, version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceLinux(version string) api.ArtifactSource {
	name := "linux"
	path := fmt.Sprintf("https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-%s.tar.xz", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceNcurses(version string) api.ArtifactSource {
	name := "ncurses"
	path := fmt.Sprintf("https://invisible-mirror.net/archives/ncurses/current/ncurses-%s.tgz", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceOpenssl(version string) api.ArtifactSource {
	name := "openssl"
	path := fmt.Sprintf("https://www.openssl.org/source/openssl-%s.tar.gz", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourcePerl(version string) api.ArtifactSource {
	name := "perl"
	path := fmt.Sprintf("https://www.cpan.org/src/5.0/perl-%s.tar.xz", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourcePython(version string) api.ArtifactSource {
	name := "python"
	path := fmt.Sprintf("https://www.python.org/ftp/python/%s/Python-%s.tar.xz", version, version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceUnzipPatchFixes(version string) api.ArtifactSource {
	name := "unzip-patch-fixes"
	path := fmt.Sprintf("https://www.linuxfromscratch.org/patches/downloads/unzip/unzip-%s-consolidated_fixes-1.patch", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceUnzipPatchGcc14(version string) api.ArtifactSource {
	name := "unzip-patch-gcc14"
	path := fmt.Sprintf("https://www.linuxfromscratch.org/patches/downloads/unzip/unzip-%s-gcc14-1.patch", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceUnzip(version string) api.ArtifactSource {
	name := "unzip"
	versionClean := strings.ReplaceAll(version, ".", "")
	path := fmt.Sprintf("https://cytranet-dal.dl.sourceforge.net/project/infozip/UnZip%%206.x%%20%%28latest%%29/UnZip%%206.0/unzip%s.tar.gz?viasf=1", versionClean)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceUtilLinux(version string) api.ArtifactSource {
	name := "util-linux"
	path := fmt.Sprintf("https://www.kernel.org/pub/linux/utils/util-linux/v2.41/util-linux-%s.tar.xz", version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceXz(version string) api.ArtifactSource {
	name := "xz"
	path := fmt.Sprintf("https://github.com/tukaani-project/xz/releases/download/v%s/xz-%s.tar.xz", version, version)

	return artifact.NewArtifactSource(name, path).Build()
}

func SourceZlib(version string) api.ArtifactSource {
	name := "zlib"
	path := fmt.Sprintf("https://zlib.net/fossils/zlib-%s.tar.gz", version)

	return artifact.NewArtifactSource(name, path).Build()
}
