// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v4.25.4
// source: v0/archive/archive.proto

package archive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArchivePullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePullRequest) Reset() {
	*x = ArchivePullRequest{}
	mi := &file_v0_archive_archive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePullRequest) ProtoMessage() {}

func (x *ArchivePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v0_archive_archive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePullRequest.ProtoReflect.Descriptor instead.
func (*ArchivePullRequest) Descriptor() ([]byte, []int) {
	return file_v0_archive_archive_proto_rawDescGZIP(), []int{0}
}

func (x *ArchivePullRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type ArchivePushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePushRequest) Reset() {
	*x = ArchivePushRequest{}
	mi := &file_v0_archive_archive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePushRequest) ProtoMessage() {}

func (x *ArchivePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v0_archive_archive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePushRequest.ProtoReflect.Descriptor instead.
func (*ArchivePushRequest) Descriptor() ([]byte, []int) {
	return file_v0_archive_archive_proto_rawDescGZIP(), []int{1}
}

func (x *ArchivePushRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArchivePushRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ArchivePushRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type ArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveResponse) Reset() {
	*x = ArchiveResponse{}
	mi := &file_v0_archive_archive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveResponse) ProtoMessage() {}

func (x *ArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v0_archive_archive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveResponse.ProtoReflect.Descriptor instead.
func (*ArchiveResponse) Descriptor() ([]byte, []int) {
	return file_v0_archive_archive_proto_rawDescGZIP(), []int{2}
}

type ArchivePullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePullResponse) Reset() {
	*x = ArchivePullResponse{}
	mi := &file_v0_archive_archive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePullResponse) ProtoMessage() {}

func (x *ArchivePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v0_archive_archive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePullResponse.ProtoReflect.Descriptor instead.
func (*ArchivePullResponse) Descriptor() ([]byte, []int) {
	return file_v0_archive_archive_proto_rawDescGZIP(), []int{3}
}

func (x *ArchivePullResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v0_archive_archive_proto protoreflect.FileDescriptor

var file_v0_archive_archive_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x30, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x76, 0x6f, 0x72, 0x70,
	0x61, 0x6c, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x30, 0x22, 0x2c, 0x0a,
	0x12, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x12, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29,
	0x0a, 0x13, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x92, 0x02, 0x0a, 0x0e, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x05,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x25, 0x2e, 0x76, 0x6f, 0x72, 0x70, 0x61, 0x6c, 0x2e, 0x61,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x76,
	0x6f, 0x72, 0x70, 0x61, 0x6c, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x30,
	0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x57, 0x0a, 0x04, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x25, 0x2e, 0x76, 0x6f, 0x72, 0x70, 0x61,
	0x6c, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x76, 0x6f, 0x72, 0x70, 0x61, 0x6c, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x2e, 0x76, 0x30, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x53, 0x0a, 0x04, 0x50, 0x75, 0x73,
	0x68, 0x12, 0x25, 0x2e, 0x76, 0x6f, 0x72, 0x70, 0x61, 0x6c, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x76, 0x6f, 0x72, 0x70, 0x61,
	0x6c, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x4c, 0x54,
	0x2d, 0x46, 0x34, 0x2d, 0x4c, 0x4c, 0x43, 0x2f, 0x76, 0x6f, 0x72, 0x70, 0x61, 0x6c, 0x2f, 0x73,
	0x64, 0x6b, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v0_archive_archive_proto_rawDescOnce sync.Once
	file_v0_archive_archive_proto_rawDescData = file_v0_archive_archive_proto_rawDesc
)

func file_v0_archive_archive_proto_rawDescGZIP() []byte {
	file_v0_archive_archive_proto_rawDescOnce.Do(func() {
		file_v0_archive_archive_proto_rawDescData = protoimpl.X.CompressGZIP(file_v0_archive_archive_proto_rawDescData)
	})
	return file_v0_archive_archive_proto_rawDescData
}

var file_v0_archive_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v0_archive_archive_proto_goTypes = []any{
	(*ArchivePullRequest)(nil),  // 0: vorpal.archive.v0.ArchivePullRequest
	(*ArchivePushRequest)(nil),  // 1: vorpal.archive.v0.ArchivePushRequest
	(*ArchiveResponse)(nil),     // 2: vorpal.archive.v0.ArchiveResponse
	(*ArchivePullResponse)(nil), // 3: vorpal.archive.v0.ArchivePullResponse
}
var file_v0_archive_archive_proto_depIdxs = []int32{
	0, // 0: vorpal.archive.v0.ArchiveService.Check:input_type -> vorpal.archive.v0.ArchivePullRequest
	0, // 1: vorpal.archive.v0.ArchiveService.Pull:input_type -> vorpal.archive.v0.ArchivePullRequest
	1, // 2: vorpal.archive.v0.ArchiveService.Push:input_type -> vorpal.archive.v0.ArchivePushRequest
	2, // 3: vorpal.archive.v0.ArchiveService.Check:output_type -> vorpal.archive.v0.ArchiveResponse
	3, // 4: vorpal.archive.v0.ArchiveService.Pull:output_type -> vorpal.archive.v0.ArchivePullResponse
	2, // 5: vorpal.archive.v0.ArchiveService.Push:output_type -> vorpal.archive.v0.ArchiveResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v0_archive_archive_proto_init() }
func file_v0_archive_archive_proto_init() {
	if File_v0_archive_archive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v0_archive_archive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v0_archive_archive_proto_goTypes,
		DependencyIndexes: file_v0_archive_archive_proto_depIdxs,
		MessageInfos:      file_v0_archive_archive_proto_msgTypes,
	}.Build()
	File_v0_archive_archive_proto = out.File
	file_v0_archive_archive_proto_rawDesc = nil
	file_v0_archive_archive_proto_goTypes = nil
	file_v0_archive_archive_proto_depIdxs = nil
}
