# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vorpal_sdk.api.archive import archive_pb2 as archive_dot_archive__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in archive/archive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArchiveServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/vorpal.archive.ArchiveService/Check',
                request_serializer=archive_dot_archive__pb2.ArchivePullRequest.SerializeToString,
                response_deserializer=archive_dot_archive__pb2.ArchiveResponse.FromString,
                _registered_method=True)
        self.Pull = channel.unary_stream(
                '/vorpal.archive.ArchiveService/Pull',
                request_serializer=archive_dot_archive__pb2.ArchivePullRequest.SerializeToString,
                response_deserializer=archive_dot_archive__pb2.ArchivePullResponse.FromString,
                _registered_method=True)
        self.Push = channel.stream_unary(
                '/vorpal.archive.ArchiveService/Push',
                request_serializer=archive_dot_archive__pb2.ArchivePushRequest.SerializeToString,
                response_deserializer=archive_dot_archive__pb2.ArchiveResponse.FromString,
                _registered_method=True)


class ArchiveServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchiveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=archive_dot_archive__pb2.ArchivePullRequest.FromString,
                    response_serializer=archive_dot_archive__pb2.ArchiveResponse.SerializeToString,
            ),
            'Pull': grpc.unary_stream_rpc_method_handler(
                    servicer.Pull,
                    request_deserializer=archive_dot_archive__pb2.ArchivePullRequest.FromString,
                    response_serializer=archive_dot_archive__pb2.ArchivePullResponse.SerializeToString,
            ),
            'Push': grpc.stream_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=archive_dot_archive__pb2.ArchivePushRequest.FromString,
                    response_serializer=archive_dot_archive__pb2.ArchiveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vorpal.archive.ArchiveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vorpal.archive.ArchiveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArchiveService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vorpal.archive.ArchiveService/Check',
            archive_dot_archive__pb2.ArchivePullRequest.SerializeToString,
            archive_dot_archive__pb2.ArchiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vorpal.archive.ArchiveService/Pull',
            archive_dot_archive__pb2.ArchivePullRequest.SerializeToString,
            archive_dot_archive__pb2.ArchivePullResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vorpal.archive.ArchiveService/Push',
            archive_dot_archive__pb2.ArchivePushRequest.SerializeToString,
            archive_dot_archive__pb2.ArchiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
