# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: archive/archive.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'archive/archive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61rchive/archive.proto\x12\x0evorpal.archive\"7\n\x12\x41rchivePullRequest\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"E\n\x12\x41rchivePushRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\"\x11\n\x0f\x41rchiveResponse\"#\n\x13\x41rchivePullResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x80\x02\n\x0e\x41rchiveService\x12L\n\x05\x43heck\x12\".vorpal.archive.ArchivePullRequest\x1a\x1f.vorpal.archive.ArchiveResponse\x12Q\n\x04Pull\x12\".vorpal.archive.ArchivePullRequest\x1a#.vorpal.archive.ArchivePullResponse0\x01\x12M\n\x04Push\x12\".vorpal.archive.ArchivePushRequest\x1a\x1f.vorpal.archive.ArchiveResponse(\x01\x42\x35Z3github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/archiveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archive.archive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/archive'
  _globals['_ARCHIVEPULLREQUEST']._serialized_start=41
  _globals['_ARCHIVEPULLREQUEST']._serialized_end=96
  _globals['_ARCHIVEPUSHREQUEST']._serialized_start=98
  _globals['_ARCHIVEPUSHREQUEST']._serialized_end=167
  _globals['_ARCHIVERESPONSE']._serialized_start=169
  _globals['_ARCHIVERESPONSE']._serialized_end=186
  _globals['_ARCHIVEPULLRESPONSE']._serialized_start=188
  _globals['_ARCHIVEPULLRESPONSE']._serialized_end=223
  _globals['_ARCHIVESERVICE']._serialized_start=226
  _globals['_ARCHIVESERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
