# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vorpal_sdk.api.artifact import artifact_pb2 as artifact_dot_artifact__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in artifact/artifact_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArtifactServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArtifact = channel.unary_unary(
                '/vorpal.artifact.ArtifactService/GetArtifact',
                request_serializer=artifact_dot_artifact__pb2.ArtifactRequest.SerializeToString,
                response_deserializer=artifact_dot_artifact__pb2.Artifact.FromString,
                _registered_method=True)
        self.GetArtifactAlias = channel.unary_unary(
                '/vorpal.artifact.ArtifactService/GetArtifactAlias',
                request_serializer=artifact_dot_artifact__pb2.GetArtifactAliasRequest.SerializeToString,
                response_deserializer=artifact_dot_artifact__pb2.GetArtifactAliasResponse.FromString,
                _registered_method=True)
        self.GetArtifacts = channel.unary_unary(
                '/vorpal.artifact.ArtifactService/GetArtifacts',
                request_serializer=artifact_dot_artifact__pb2.ArtifactsRequest.SerializeToString,
                response_deserializer=artifact_dot_artifact__pb2.ArtifactsResponse.FromString,
                _registered_method=True)
        self.StoreArtifact = channel.unary_unary(
                '/vorpal.artifact.ArtifactService/StoreArtifact',
                request_serializer=artifact_dot_artifact__pb2.StoreArtifactRequest.SerializeToString,
                response_deserializer=artifact_dot_artifact__pb2.ArtifactResponse.FromString,
                _registered_method=True)


class ArtifactServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifactAlias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtifactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=artifact_dot_artifact__pb2.ArtifactRequest.FromString,
                    response_serializer=artifact_dot_artifact__pb2.Artifact.SerializeToString,
            ),
            'GetArtifactAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifactAlias,
                    request_deserializer=artifact_dot_artifact__pb2.GetArtifactAliasRequest.FromString,
                    response_serializer=artifact_dot_artifact__pb2.GetArtifactAliasResponse.SerializeToString,
            ),
            'GetArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifacts,
                    request_deserializer=artifact_dot_artifact__pb2.ArtifactsRequest.FromString,
                    response_serializer=artifact_dot_artifact__pb2.ArtifactsResponse.SerializeToString,
            ),
            'StoreArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreArtifact,
                    request_deserializer=artifact_dot_artifact__pb2.StoreArtifactRequest.FromString,
                    response_serializer=artifact_dot_artifact__pb2.ArtifactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vorpal.artifact.ArtifactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vorpal.artifact.ArtifactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtifactService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vorpal.artifact.ArtifactService/GetArtifact',
            artifact_dot_artifact__pb2.ArtifactRequest.SerializeToString,
            artifact_dot_artifact__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifactAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vorpal.artifact.ArtifactService/GetArtifactAlias',
            artifact_dot_artifact__pb2.GetArtifactAliasRequest.SerializeToString,
            artifact_dot_artifact__pb2.GetArtifactAliasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vorpal.artifact.ArtifactService/GetArtifacts',
            artifact_dot_artifact__pb2.ArtifactsRequest.SerializeToString,
            artifact_dot_artifact__pb2.ArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vorpal.artifact.ArtifactService/StoreArtifact',
            artifact_dot_artifact__pb2.StoreArtifactRequest.SerializeToString,
            artifact_dot_artifact__pb2.ArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
