// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: artifact/artifact.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "vorpal.artifact";

export enum ArtifactSystem {
  UNKNOWN_SYSTEM = 0,
  AARCH64_DARWIN = 1,
  AARCH64_LINUX = 2,
  X8664_DARWIN = 3,
  X8664_LINUX = 4,
  UNRECOGNIZED = -1,
}

export function artifactSystemFromJSON(object: any): ArtifactSystem {
  switch (object) {
    case 0:
    case "UNKNOWN_SYSTEM":
      return ArtifactSystem.UNKNOWN_SYSTEM;
    case 1:
    case "AARCH64_DARWIN":
      return ArtifactSystem.AARCH64_DARWIN;
    case 2:
    case "AARCH64_LINUX":
      return ArtifactSystem.AARCH64_LINUX;
    case 3:
    case "X8664_DARWIN":
      return ArtifactSystem.X8664_DARWIN;
    case 4:
    case "X8664_LINUX":
      return ArtifactSystem.X8664_LINUX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ArtifactSystem.UNRECOGNIZED;
  }
}

export function artifactSystemToJSON(object: ArtifactSystem): string {
  switch (object) {
    case ArtifactSystem.UNKNOWN_SYSTEM:
      return "UNKNOWN_SYSTEM";
    case ArtifactSystem.AARCH64_DARWIN:
      return "AARCH64_DARWIN";
    case ArtifactSystem.AARCH64_LINUX:
      return "AARCH64_LINUX";
    case ArtifactSystem.X8664_DARWIN:
      return "X8664_DARWIN";
    case ArtifactSystem.X8664_LINUX:
      return "X8664_LINUX";
    case ArtifactSystem.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ArtifactSource {
  digest?: string | undefined;
  excludes: string[];
  includes: string[];
  name: string;
  path: string;
}

export interface ArtifactStepSecret {
  name: string;
  value: string;
}

export interface ArtifactStep {
  entrypoint?: string | undefined;
  script?: string | undefined;
  secrets: ArtifactStepSecret[];
  arguments: string[];
  artifacts: string[];
  environments: string[];
}

export interface Artifact {
  target: ArtifactSystem;
  sources: ArtifactSource[];
  steps: ArtifactStep[];
  systems: ArtifactSystem[];
  aliases: string[];
  name: string;
}

export interface ArtifactRequest {
  digest: string;
  namespace: string;
}

export interface ArtifactResponse {
  digest: string;
}

export interface ArtifactsRequest {
  digests: string[];
  namespace: string;
}

export interface ArtifactsResponse {
  digests: string[];
}

export interface GetArtifactAliasRequest {
  system: ArtifactSystem;
  name: string;
  namespace: string;
  tag: string;
}

export interface GetArtifactAliasResponse {
  digest: string;
}

export interface StoreArtifactRequest {
  artifact?: Artifact | undefined;
  artifact_aliases: string[];
  artifact_namespace: string;
}

function createBaseArtifactSource(): ArtifactSource {
  return { digest: undefined, excludes: [], includes: [], name: "", path: "" };
}

export const ArtifactSource: MessageFns<ArtifactSource> = {
  encode(message: ArtifactSource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.digest !== undefined) {
      writer.uint32(10).string(message.digest);
    }
    for (const v of message.excludes) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.includes) {
      writer.uint32(26).string(v!);
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.path !== "") {
      writer.uint32(42).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArtifactSource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifactSource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.excludes.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.includes.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArtifactSource {
    return {
      digest: isSet(object.digest) ? globalThis.String(object.digest) : undefined,
      excludes: globalThis.Array.isArray(object?.excludes) ? object.excludes.map((e: any) => globalThis.String(e)) : [],
      includes: globalThis.Array.isArray(object?.includes) ? object.includes.map((e: any) => globalThis.String(e)) : [],
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      path: isSet(object.path) ? globalThis.String(object.path) : "",
    };
  },

  toJSON(message: ArtifactSource): unknown {
    const obj: any = {};
    if (message.digest !== undefined) {
      obj.digest = message.digest;
    }
    if (message.excludes?.length) {
      obj.excludes = message.excludes;
    }
    if (message.includes?.length) {
      obj.includes = message.includes;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArtifactSource>, I>>(base?: I): ArtifactSource {
    return ArtifactSource.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArtifactSource>, I>>(object: I): ArtifactSource {
    const message = createBaseArtifactSource();
    message.digest = object.digest ?? undefined;
    message.excludes = object.excludes?.map((e) => e) || [];
    message.includes = object.includes?.map((e) => e) || [];
    message.name = object.name ?? "";
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseArtifactStepSecret(): ArtifactStepSecret {
  return { name: "", value: "" };
}

export const ArtifactStepSecret: MessageFns<ArtifactStepSecret> = {
  encode(message: ArtifactStepSecret, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArtifactStepSecret {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifactStepSecret();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArtifactStepSecret {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ArtifactStepSecret): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArtifactStepSecret>, I>>(base?: I): ArtifactStepSecret {
    return ArtifactStepSecret.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArtifactStepSecret>, I>>(object: I): ArtifactStepSecret {
    const message = createBaseArtifactStepSecret();
    message.name = object.name ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseArtifactStep(): ArtifactStep {
  return { entrypoint: undefined, script: undefined, secrets: [], arguments: [], artifacts: [], environments: [] };
}

export const ArtifactStep: MessageFns<ArtifactStep> = {
  encode(message: ArtifactStep, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entrypoint !== undefined) {
      writer.uint32(10).string(message.entrypoint);
    }
    if (message.script !== undefined) {
      writer.uint32(18).string(message.script);
    }
    for (const v of message.secrets) {
      ArtifactStepSecret.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.arguments) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.artifacts) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.environments) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArtifactStep {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifactStep();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entrypoint = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.script = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.secrets.push(ArtifactStepSecret.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.arguments.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.artifacts.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.environments.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArtifactStep {
    return {
      entrypoint: isSet(object.entrypoint) ? globalThis.String(object.entrypoint) : undefined,
      script: isSet(object.script) ? globalThis.String(object.script) : undefined,
      secrets: globalThis.Array.isArray(object?.secrets)
        ? object.secrets.map((e: any) => ArtifactStepSecret.fromJSON(e))
        : [],
      arguments: globalThis.Array.isArray(object?.arguments)
        ? object.arguments.map((e: any) => globalThis.String(e))
        : [],
      artifacts: globalThis.Array.isArray(object?.artifacts)
        ? object.artifacts.map((e: any) => globalThis.String(e))
        : [],
      environments: globalThis.Array.isArray(object?.environments)
        ? object.environments.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ArtifactStep): unknown {
    const obj: any = {};
    if (message.entrypoint !== undefined) {
      obj.entrypoint = message.entrypoint;
    }
    if (message.script !== undefined) {
      obj.script = message.script;
    }
    if (message.secrets?.length) {
      obj.secrets = message.secrets.map((e) => ArtifactStepSecret.toJSON(e));
    }
    if (message.arguments?.length) {
      obj.arguments = message.arguments;
    }
    if (message.artifacts?.length) {
      obj.artifacts = message.artifacts;
    }
    if (message.environments?.length) {
      obj.environments = message.environments;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArtifactStep>, I>>(base?: I): ArtifactStep {
    return ArtifactStep.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArtifactStep>, I>>(object: I): ArtifactStep {
    const message = createBaseArtifactStep();
    message.entrypoint = object.entrypoint ?? undefined;
    message.script = object.script ?? undefined;
    message.secrets = object.secrets?.map((e) => ArtifactStepSecret.fromPartial(e)) || [];
    message.arguments = object.arguments?.map((e) => e) || [];
    message.artifacts = object.artifacts?.map((e) => e) || [];
    message.environments = object.environments?.map((e) => e) || [];
    return message;
  },
};

function createBaseArtifact(): Artifact {
  return { target: 0, sources: [], steps: [], systems: [], aliases: [], name: "" };
}

export const Artifact: MessageFns<Artifact> = {
  encode(message: Artifact, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.target !== 0) {
      writer.uint32(8).int32(message.target);
    }
    for (const v of message.sources) {
      ArtifactSource.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.steps) {
      ArtifactStep.encode(v!, writer.uint32(26).fork()).join();
    }
    writer.uint32(34).fork();
    for (const v of message.systems) {
      writer.int32(v);
    }
    writer.join();
    for (const v of message.aliases) {
      writer.uint32(42).string(v!);
    }
    if (message.name !== "") {
      writer.uint32(50).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Artifact {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifact();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.target = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sources.push(ArtifactSource.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.steps.push(ArtifactStep.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.systems.push(reader.int32() as any);

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.systems.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.aliases.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Artifact {
    return {
      target: isSet(object.target) ? artifactSystemFromJSON(object.target) : 0,
      sources: globalThis.Array.isArray(object?.sources)
        ? object.sources.map((e: any) => ArtifactSource.fromJSON(e))
        : [],
      steps: globalThis.Array.isArray(object?.steps) ? object.steps.map((e: any) => ArtifactStep.fromJSON(e)) : [],
      systems: globalThis.Array.isArray(object?.systems)
        ? object.systems.map((e: any) => artifactSystemFromJSON(e))
        : [],
      aliases: globalThis.Array.isArray(object?.aliases) ? object.aliases.map((e: any) => globalThis.String(e)) : [],
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: Artifact): unknown {
    const obj: any = {};
    if (message.target !== 0) {
      obj.target = artifactSystemToJSON(message.target);
    }
    if (message.sources?.length) {
      obj.sources = message.sources.map((e) => ArtifactSource.toJSON(e));
    }
    if (message.steps?.length) {
      obj.steps = message.steps.map((e) => ArtifactStep.toJSON(e));
    }
    if (message.systems?.length) {
      obj.systems = message.systems.map((e) => artifactSystemToJSON(e));
    }
    if (message.aliases?.length) {
      obj.aliases = message.aliases;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Artifact>, I>>(base?: I): Artifact {
    return Artifact.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Artifact>, I>>(object: I): Artifact {
    const message = createBaseArtifact();
    message.target = object.target ?? 0;
    message.sources = object.sources?.map((e) => ArtifactSource.fromPartial(e)) || [];
    message.steps = object.steps?.map((e) => ArtifactStep.fromPartial(e)) || [];
    message.systems = object.systems?.map((e) => e) || [];
    message.aliases = object.aliases?.map((e) => e) || [];
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseArtifactRequest(): ArtifactRequest {
  return { digest: "", namespace: "" };
}

export const ArtifactRequest: MessageFns<ArtifactRequest> = {
  encode(message: ArtifactRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.digest !== "") {
      writer.uint32(10).string(message.digest);
    }
    if (message.namespace !== "") {
      writer.uint32(18).string(message.namespace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArtifactRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifactRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArtifactRequest {
    return {
      digest: isSet(object.digest) ? globalThis.String(object.digest) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
    };
  },

  toJSON(message: ArtifactRequest): unknown {
    const obj: any = {};
    if (message.digest !== "") {
      obj.digest = message.digest;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArtifactRequest>, I>>(base?: I): ArtifactRequest {
    return ArtifactRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArtifactRequest>, I>>(object: I): ArtifactRequest {
    const message = createBaseArtifactRequest();
    message.digest = object.digest ?? "";
    message.namespace = object.namespace ?? "";
    return message;
  },
};

function createBaseArtifactResponse(): ArtifactResponse {
  return { digest: "" };
}

export const ArtifactResponse: MessageFns<ArtifactResponse> = {
  encode(message: ArtifactResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.digest !== "") {
      writer.uint32(10).string(message.digest);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArtifactResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifactResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArtifactResponse {
    return { digest: isSet(object.digest) ? globalThis.String(object.digest) : "" };
  },

  toJSON(message: ArtifactResponse): unknown {
    const obj: any = {};
    if (message.digest !== "") {
      obj.digest = message.digest;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArtifactResponse>, I>>(base?: I): ArtifactResponse {
    return ArtifactResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArtifactResponse>, I>>(object: I): ArtifactResponse {
    const message = createBaseArtifactResponse();
    message.digest = object.digest ?? "";
    return message;
  },
};

function createBaseArtifactsRequest(): ArtifactsRequest {
  return { digests: [], namespace: "" };
}

export const ArtifactsRequest: MessageFns<ArtifactsRequest> = {
  encode(message: ArtifactsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.digests) {
      writer.uint32(10).string(v!);
    }
    if (message.namespace !== "") {
      writer.uint32(18).string(message.namespace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArtifactsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifactsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.digests.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArtifactsRequest {
    return {
      digests: globalThis.Array.isArray(object?.digests) ? object.digests.map((e: any) => globalThis.String(e)) : [],
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
    };
  },

  toJSON(message: ArtifactsRequest): unknown {
    const obj: any = {};
    if (message.digests?.length) {
      obj.digests = message.digests;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArtifactsRequest>, I>>(base?: I): ArtifactsRequest {
    return ArtifactsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArtifactsRequest>, I>>(object: I): ArtifactsRequest {
    const message = createBaseArtifactsRequest();
    message.digests = object.digests?.map((e) => e) || [];
    message.namespace = object.namespace ?? "";
    return message;
  },
};

function createBaseArtifactsResponse(): ArtifactsResponse {
  return { digests: [] };
}

export const ArtifactsResponse: MessageFns<ArtifactsResponse> = {
  encode(message: ArtifactsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.digests) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArtifactsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifactsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.digests.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArtifactsResponse {
    return {
      digests: globalThis.Array.isArray(object?.digests) ? object.digests.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: ArtifactsResponse): unknown {
    const obj: any = {};
    if (message.digests?.length) {
      obj.digests = message.digests;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArtifactsResponse>, I>>(base?: I): ArtifactsResponse {
    return ArtifactsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArtifactsResponse>, I>>(object: I): ArtifactsResponse {
    const message = createBaseArtifactsResponse();
    message.digests = object.digests?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetArtifactAliasRequest(): GetArtifactAliasRequest {
  return { system: 0, name: "", namespace: "", tag: "" };
}

export const GetArtifactAliasRequest: MessageFns<GetArtifactAliasRequest> = {
  encode(message: GetArtifactAliasRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.system !== 0) {
      writer.uint32(8).int32(message.system);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.namespace !== "") {
      writer.uint32(26).string(message.namespace);
    }
    if (message.tag !== "") {
      writer.uint32(34).string(message.tag);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetArtifactAliasRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetArtifactAliasRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.system = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tag = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetArtifactAliasRequest {
    return {
      system: isSet(object.system) ? artifactSystemFromJSON(object.system) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      tag: isSet(object.tag) ? globalThis.String(object.tag) : "",
    };
  },

  toJSON(message: GetArtifactAliasRequest): unknown {
    const obj: any = {};
    if (message.system !== 0) {
      obj.system = artifactSystemToJSON(message.system);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.tag !== "") {
      obj.tag = message.tag;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetArtifactAliasRequest>, I>>(base?: I): GetArtifactAliasRequest {
    return GetArtifactAliasRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetArtifactAliasRequest>, I>>(object: I): GetArtifactAliasRequest {
    const message = createBaseGetArtifactAliasRequest();
    message.system = object.system ?? 0;
    message.name = object.name ?? "";
    message.namespace = object.namespace ?? "";
    message.tag = object.tag ?? "";
    return message;
  },
};

function createBaseGetArtifactAliasResponse(): GetArtifactAliasResponse {
  return { digest: "" };
}

export const GetArtifactAliasResponse: MessageFns<GetArtifactAliasResponse> = {
  encode(message: GetArtifactAliasResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.digest !== "") {
      writer.uint32(10).string(message.digest);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetArtifactAliasResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetArtifactAliasResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetArtifactAliasResponse {
    return { digest: isSet(object.digest) ? globalThis.String(object.digest) : "" };
  },

  toJSON(message: GetArtifactAliasResponse): unknown {
    const obj: any = {};
    if (message.digest !== "") {
      obj.digest = message.digest;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetArtifactAliasResponse>, I>>(base?: I): GetArtifactAliasResponse {
    return GetArtifactAliasResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetArtifactAliasResponse>, I>>(object: I): GetArtifactAliasResponse {
    const message = createBaseGetArtifactAliasResponse();
    message.digest = object.digest ?? "";
    return message;
  },
};

function createBaseStoreArtifactRequest(): StoreArtifactRequest {
  return { artifact: undefined, artifact_aliases: [], artifact_namespace: "" };
}

export const StoreArtifactRequest: MessageFns<StoreArtifactRequest> = {
  encode(message: StoreArtifactRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.artifact !== undefined) {
      Artifact.encode(message.artifact, writer.uint32(10).fork()).join();
    }
    for (const v of message.artifact_aliases) {
      writer.uint32(18).string(v!);
    }
    if (message.artifact_namespace !== "") {
      writer.uint32(26).string(message.artifact_namespace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreArtifactRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreArtifactRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.artifact = Artifact.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.artifact_aliases.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.artifact_namespace = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreArtifactRequest {
    return {
      artifact: isSet(object.artifact) ? Artifact.fromJSON(object.artifact) : undefined,
      artifact_aliases: globalThis.Array.isArray(object?.artifactAliases)
        ? object.artifactAliases.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.artifact_aliases)
        ? object.artifact_aliases.map((e: any) => globalThis.String(e))
        : [],
      artifact_namespace: isSet(object.artifactNamespace)
        ? globalThis.String(object.artifactNamespace)
        : isSet(object.artifact_namespace)
        ? globalThis.String(object.artifact_namespace)
        : "",
    };
  },

  toJSON(message: StoreArtifactRequest): unknown {
    const obj: any = {};
    if (message.artifact !== undefined) {
      obj.artifact = Artifact.toJSON(message.artifact);
    }
    if (message.artifact_aliases?.length) {
      obj.artifactAliases = message.artifact_aliases;
    }
    if (message.artifact_namespace !== "") {
      obj.artifactNamespace = message.artifact_namespace;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoreArtifactRequest>, I>>(base?: I): StoreArtifactRequest {
    return StoreArtifactRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoreArtifactRequest>, I>>(object: I): StoreArtifactRequest {
    const message = createBaseStoreArtifactRequest();
    message.artifact = (object.artifact !== undefined && object.artifact !== null)
      ? Artifact.fromPartial(object.artifact)
      : undefined;
    message.artifact_aliases = object.artifact_aliases?.map((e) => e) || [];
    message.artifact_namespace = object.artifact_namespace ?? "";
    return message;
  },
};

export type ArtifactServiceService = typeof ArtifactServiceService;
export const ArtifactServiceService = {
  getArtifact: {
    path: "/vorpal.artifact.ArtifactService/GetArtifact" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArtifactRequest): Buffer => Buffer.from(ArtifactRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArtifactRequest => ArtifactRequest.decode(value),
    responseSerialize: (value: Artifact): Buffer => Buffer.from(Artifact.encode(value).finish()),
    responseDeserialize: (value: Buffer): Artifact => Artifact.decode(value),
  },
  getArtifactAlias: {
    path: "/vorpal.artifact.ArtifactService/GetArtifactAlias" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetArtifactAliasRequest): Buffer =>
      Buffer.from(GetArtifactAliasRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetArtifactAliasRequest => GetArtifactAliasRequest.decode(value),
    responseSerialize: (value: GetArtifactAliasResponse): Buffer =>
      Buffer.from(GetArtifactAliasResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetArtifactAliasResponse => GetArtifactAliasResponse.decode(value),
  },
  getArtifacts: {
    path: "/vorpal.artifact.ArtifactService/GetArtifacts" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArtifactsRequest): Buffer => Buffer.from(ArtifactsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArtifactsRequest => ArtifactsRequest.decode(value),
    responseSerialize: (value: ArtifactsResponse): Buffer => Buffer.from(ArtifactsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArtifactsResponse => ArtifactsResponse.decode(value),
  },
  storeArtifact: {
    path: "/vorpal.artifact.ArtifactService/StoreArtifact" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: StoreArtifactRequest): Buffer => Buffer.from(StoreArtifactRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): StoreArtifactRequest => StoreArtifactRequest.decode(value),
    responseSerialize: (value: ArtifactResponse): Buffer => Buffer.from(ArtifactResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArtifactResponse => ArtifactResponse.decode(value),
  },
} as const;

export interface ArtifactServiceServer extends UntypedServiceImplementation {
  getArtifact: handleUnaryCall<ArtifactRequest, Artifact>;
  getArtifactAlias: handleUnaryCall<GetArtifactAliasRequest, GetArtifactAliasResponse>;
  getArtifacts: handleUnaryCall<ArtifactsRequest, ArtifactsResponse>;
  storeArtifact: handleUnaryCall<StoreArtifactRequest, ArtifactResponse>;
}

export interface ArtifactServiceClient extends Client {
  getArtifact(
    request: ArtifactRequest,
    callback: (error: ServiceError | null, response: Artifact) => void,
  ): ClientUnaryCall;
  getArtifact(
    request: ArtifactRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Artifact) => void,
  ): ClientUnaryCall;
  getArtifact(
    request: ArtifactRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Artifact) => void,
  ): ClientUnaryCall;
  getArtifactAlias(
    request: GetArtifactAliasRequest,
    callback: (error: ServiceError | null, response: GetArtifactAliasResponse) => void,
  ): ClientUnaryCall;
  getArtifactAlias(
    request: GetArtifactAliasRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetArtifactAliasResponse) => void,
  ): ClientUnaryCall;
  getArtifactAlias(
    request: GetArtifactAliasRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetArtifactAliasResponse) => void,
  ): ClientUnaryCall;
  getArtifacts(
    request: ArtifactsRequest,
    callback: (error: ServiceError | null, response: ArtifactsResponse) => void,
  ): ClientUnaryCall;
  getArtifacts(
    request: ArtifactsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArtifactsResponse) => void,
  ): ClientUnaryCall;
  getArtifacts(
    request: ArtifactsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArtifactsResponse) => void,
  ): ClientUnaryCall;
  storeArtifact(
    request: StoreArtifactRequest,
    callback: (error: ServiceError | null, response: ArtifactResponse) => void,
  ): ClientUnaryCall;
  storeArtifact(
    request: StoreArtifactRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArtifactResponse) => void,
  ): ClientUnaryCall;
  storeArtifact(
    request: StoreArtifactRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArtifactResponse) => void,
  ): ClientUnaryCall;
}

export const ArtifactServiceClient = makeGenericClientConstructor(
  ArtifactServiceService,
  "vorpal.artifact.ArtifactService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ArtifactServiceClient;
  service: typeof ArtifactServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
