// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: agent/agent.proto

package agent

import (
	artifact "github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/artifact"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareArtifactRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUnlock    bool                   `protobuf:"varint,1,opt,name=artifact_unlock,json=artifactUnlock,proto3" json:"artifact_unlock,omitempty"`
	ArtifactContext   string                 `protobuf:"bytes,2,opt,name=artifact_context,json=artifactContext,proto3" json:"artifact_context,omitempty"`
	ArtifactNamespace string                 `protobuf:"bytes,3,opt,name=artifact_namespace,json=artifactNamespace,proto3" json:"artifact_namespace,omitempty"`
	Registry          string                 `protobuf:"bytes,4,opt,name=registry,proto3" json:"registry,omitempty"`
	Artifact          *artifact.Artifact     `protobuf:"bytes,5,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareArtifactRequest) Reset() {
	*x = PrepareArtifactRequest{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareArtifactRequest) ProtoMessage() {}

func (x *PrepareArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareArtifactRequest.ProtoReflect.Descriptor instead.
func (*PrepareArtifactRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareArtifactRequest) GetArtifactUnlock() bool {
	if x != nil {
		return x.ArtifactUnlock
	}
	return false
}

func (x *PrepareArtifactRequest) GetArtifactContext() string {
	if x != nil {
		return x.ArtifactContext
	}
	return ""
}

func (x *PrepareArtifactRequest) GetArtifactNamespace() string {
	if x != nil {
		return x.ArtifactNamespace
	}
	return ""
}

func (x *PrepareArtifactRequest) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *PrepareArtifactRequest) GetArtifact() *artifact.Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type PrepareArtifactResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArtifactDigest *string                `protobuf:"bytes,1,opt,name=artifact_digest,json=artifactDigest,proto3,oneof" json:"artifact_digest,omitempty"`
	ArtifactOutput *string                `protobuf:"bytes,2,opt,name=artifact_output,json=artifactOutput,proto3,oneof" json:"artifact_output,omitempty"`
	Artifact       *artifact.Artifact     `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareArtifactResponse) Reset() {
	*x = PrepareArtifactResponse{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareArtifactResponse) ProtoMessage() {}

func (x *PrepareArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareArtifactResponse.ProtoReflect.Descriptor instead.
func (*PrepareArtifactResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareArtifactResponse) GetArtifactDigest() string {
	if x != nil && x.ArtifactDigest != nil {
		return *x.ArtifactDigest
	}
	return ""
}

func (x *PrepareArtifactResponse) GetArtifactOutput() string {
	if x != nil && x.ArtifactOutput != nil {
		return *x.ArtifactOutput
	}
	return ""
}

func (x *PrepareArtifactResponse) GetArtifact() *artifact.Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\fvorpal.agent\x1a\x17artifact/artifact.proto\"\xee\x01\n" +
	"\x16PrepareArtifactRequest\x12'\n" +
	"\x0fartifact_unlock\x18\x01 \x01(\bR\x0eartifactUnlock\x12)\n" +
	"\x10artifact_context\x18\x02 \x01(\tR\x0fartifactContext\x12-\n" +
	"\x12artifact_namespace\x18\x03 \x01(\tR\x11artifactNamespace\x12\x1a\n" +
	"\bregistry\x18\x04 \x01(\tR\bregistry\x125\n" +
	"\bartifact\x18\x05 \x01(\v2\x19.vorpal.artifact.ArtifactR\bartifact\"\xd4\x01\n" +
	"\x17PrepareArtifactResponse\x12,\n" +
	"\x0fartifact_digest\x18\x01 \x01(\tH\x00R\x0eartifactDigest\x88\x01\x01\x12,\n" +
	"\x0fartifact_output\x18\x02 \x01(\tH\x01R\x0eartifactOutput\x88\x01\x01\x125\n" +
	"\bartifact\x18\x03 \x01(\v2\x19.vorpal.artifact.ArtifactR\bartifactB\x12\n" +
	"\x10_artifact_digestB\x12\n" +
	"\x10_artifact_output2r\n" +
	"\fAgentService\x12b\n" +
	"\x0fPrepareArtifact\x12$.vorpal.agent.PrepareArtifactRequest\x1a%.vorpal.agent.PrepareArtifactResponse\"\x000\x01B3Z1github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/agentb\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_agent_proto_goTypes = []any{
	(*PrepareArtifactRequest)(nil),  // 0: vorpal.agent.PrepareArtifactRequest
	(*PrepareArtifactResponse)(nil), // 1: vorpal.agent.PrepareArtifactResponse
	(*artifact.Artifact)(nil),       // 2: vorpal.artifact.Artifact
}
var file_agent_agent_proto_depIdxs = []int32{
	2, // 0: vorpal.agent.PrepareArtifactRequest.artifact:type_name -> vorpal.artifact.Artifact
	2, // 1: vorpal.agent.PrepareArtifactResponse.artifact:type_name -> vorpal.artifact.Artifact
	0, // 2: vorpal.agent.AgentService.PrepareArtifact:input_type -> vorpal.agent.PrepareArtifactRequest
	1, // 3: vorpal.agent.AgentService.PrepareArtifact:output_type -> vorpal.agent.PrepareArtifactResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	file_agent_agent_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
