// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: archive/archive.proto

package archive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArchivePullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePullRequest) Reset() {
	*x = ArchivePullRequest{}
	mi := &file_archive_archive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePullRequest) ProtoMessage() {}

func (x *ArchivePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_archive_archive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePullRequest.ProtoReflect.Descriptor instead.
func (*ArchivePullRequest) Descriptor() ([]byte, []int) {
	return file_archive_archive_proto_rawDescGZIP(), []int{0}
}

func (x *ArchivePullRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ArchivePullRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ArchivePushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePushRequest) Reset() {
	*x = ArchivePushRequest{}
	mi := &file_archive_archive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePushRequest) ProtoMessage() {}

func (x *ArchivePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_archive_archive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePushRequest.ProtoReflect.Descriptor instead.
func (*ArchivePushRequest) Descriptor() ([]byte, []int) {
	return file_archive_archive_proto_rawDescGZIP(), []int{1}
}

func (x *ArchivePushRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArchivePushRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ArchivePushRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveResponse) Reset() {
	*x = ArchiveResponse{}
	mi := &file_archive_archive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveResponse) ProtoMessage() {}

func (x *ArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_archive_archive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveResponse.ProtoReflect.Descriptor instead.
func (*ArchiveResponse) Descriptor() ([]byte, []int) {
	return file_archive_archive_proto_rawDescGZIP(), []int{2}
}

type ArchivePullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePullResponse) Reset() {
	*x = ArchivePullResponse{}
	mi := &file_archive_archive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePullResponse) ProtoMessage() {}

func (x *ArchivePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_archive_archive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePullResponse.ProtoReflect.Descriptor instead.
func (*ArchivePullResponse) Descriptor() ([]byte, []int) {
	return file_archive_archive_proto_rawDescGZIP(), []int{3}
}

func (x *ArchivePullResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_archive_archive_proto protoreflect.FileDescriptor

const file_archive_archive_proto_rawDesc = "" +
	"\n" +
	"\x15archive/archive.proto\x12\x0evorpal.archive\"J\n" +
	"\x12ArchivePullRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"^\n" +
	"\x12ArchivePushRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"\x11\n" +
	"\x0fArchiveResponse\")\n" +
	"\x13ArchivePullResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x80\x02\n" +
	"\x0eArchiveService\x12L\n" +
	"\x05Check\x12\".vorpal.archive.ArchivePullRequest\x1a\x1f.vorpal.archive.ArchiveResponse\x12Q\n" +
	"\x04Pull\x12\".vorpal.archive.ArchivePullRequest\x1a#.vorpal.archive.ArchivePullResponse0\x01\x12M\n" +
	"\x04Push\x12\".vorpal.archive.ArchivePushRequest\x1a\x1f.vorpal.archive.ArchiveResponse(\x01B5Z3github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/archiveb\x06proto3"

var (
	file_archive_archive_proto_rawDescOnce sync.Once
	file_archive_archive_proto_rawDescData []byte
)

func file_archive_archive_proto_rawDescGZIP() []byte {
	file_archive_archive_proto_rawDescOnce.Do(func() {
		file_archive_archive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_archive_archive_proto_rawDesc), len(file_archive_archive_proto_rawDesc)))
	})
	return file_archive_archive_proto_rawDescData
}

var file_archive_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_archive_archive_proto_goTypes = []any{
	(*ArchivePullRequest)(nil),  // 0: vorpal.archive.ArchivePullRequest
	(*ArchivePushRequest)(nil),  // 1: vorpal.archive.ArchivePushRequest
	(*ArchiveResponse)(nil),     // 2: vorpal.archive.ArchiveResponse
	(*ArchivePullResponse)(nil), // 3: vorpal.archive.ArchivePullResponse
}
var file_archive_archive_proto_depIdxs = []int32{
	0, // 0: vorpal.archive.ArchiveService.Check:input_type -> vorpal.archive.ArchivePullRequest
	0, // 1: vorpal.archive.ArchiveService.Pull:input_type -> vorpal.archive.ArchivePullRequest
	1, // 2: vorpal.archive.ArchiveService.Push:input_type -> vorpal.archive.ArchivePushRequest
	2, // 3: vorpal.archive.ArchiveService.Check:output_type -> vorpal.archive.ArchiveResponse
	3, // 4: vorpal.archive.ArchiveService.Pull:output_type -> vorpal.archive.ArchivePullResponse
	2, // 5: vorpal.archive.ArchiveService.Push:output_type -> vorpal.archive.ArchiveResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_archive_archive_proto_init() }
func file_archive_archive_proto_init() {
	if File_archive_archive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_archive_archive_proto_rawDesc), len(file_archive_archive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_archive_archive_proto_goTypes,
		DependencyIndexes: file_archive_archive_proto_depIdxs,
		MessageInfos:      file_archive_archive_proto_msgTypes,
	}.Build()
	File_archive_archive_proto = out.File
	file_archive_archive_proto_goTypes = nil
	file_archive_archive_proto_depIdxs = nil
}
