// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: context/context.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Artifact, ArtifactRequest, ArtifactsRequest, ArtifactsResponse } from "../artifact/artifact.js";

export const protobufPackage = "vorpal.context";

export type ContextServiceService = typeof ContextServiceService;
export const ContextServiceService = {
  getArtifact: {
    path: "/vorpal.context.ContextService/GetArtifact" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArtifactRequest): Buffer => Buffer.from(ArtifactRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArtifactRequest => ArtifactRequest.decode(value),
    responseSerialize: (value: Artifact): Buffer => Buffer.from(Artifact.encode(value).finish()),
    responseDeserialize: (value: Buffer): Artifact => Artifact.decode(value),
  },
  getArtifacts: {
    path: "/vorpal.context.ContextService/GetArtifacts" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArtifactsRequest): Buffer => Buffer.from(ArtifactsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArtifactsRequest => ArtifactsRequest.decode(value),
    responseSerialize: (value: ArtifactsResponse): Buffer => Buffer.from(ArtifactsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArtifactsResponse => ArtifactsResponse.decode(value),
  },
} as const;

export interface ContextServiceServer extends UntypedServiceImplementation {
  getArtifact: handleUnaryCall<ArtifactRequest, Artifact>;
  getArtifacts: handleUnaryCall<ArtifactsRequest, ArtifactsResponse>;
}

export interface ContextServiceClient extends Client {
  getArtifact(
    request: ArtifactRequest,
    callback: (error: ServiceError | null, response: Artifact) => void,
  ): ClientUnaryCall;
  getArtifact(
    request: ArtifactRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Artifact) => void,
  ): ClientUnaryCall;
  getArtifact(
    request: ArtifactRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Artifact) => void,
  ): ClientUnaryCall;
  getArtifacts(
    request: ArtifactsRequest,
    callback: (error: ServiceError | null, response: ArtifactsResponse) => void,
  ): ClientUnaryCall;
  getArtifacts(
    request: ArtifactsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArtifactsResponse) => void,
  ): ClientUnaryCall;
  getArtifacts(
    request: ArtifactsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArtifactsResponse) => void,
  ): ClientUnaryCall;
}

export const ContextServiceClient = makeGenericClientConstructor(
  ContextServiceService,
  "vorpal.context.ContextService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ContextServiceClient;
  service: typeof ContextServiceService;
  serviceName: string;
};
