//! Rust SDK for defining Vorpal builds as programs.
//!
//! A build config is a binary that constructs artifacts through
//! [`context::ConfigContext`] and runs the [`cli`] entry point, which the
//! `vorpal` CLI drives over gRPC.

/// Generated gRPC clients, servers, and message types for the Vorpal
/// protobuf API under `api/`.
pub mod api {
    /// `vorpal.agent` service: prepares artifacts on behalf of a config.
    pub mod agent {
        #![allow(
            clippy::all,
            clippy::pedantic,
            clippy::allow_attributes,
            clippy::allow_attributes_without_reason,
            clippy::clone_on_ref_ptr,
            missing_docs,
            reason = "generated by tonic-prost-build"
        )]
        tonic::include_proto!("vorpal.agent");
    }

    /// `vorpal.archive` service: uploads and downloads artifact archives.
    pub mod archive {
        #![allow(
            clippy::all,
            clippy::pedantic,
            clippy::allow_attributes,
            clippy::allow_attributes_without_reason,
            clippy::clone_on_ref_ptr,
            missing_docs,
            reason = "generated by tonic-prost-build"
        )]
        tonic::include_proto!("vorpal.archive");
    }

    /// `vorpal.artifact` service and the artifact definition types.
    pub mod artifact {
        #![allow(
            clippy::all,
            clippy::pedantic,
            clippy::allow_attributes,
            clippy::allow_attributes_without_reason,
            clippy::clone_on_ref_ptr,
            missing_docs,
            reason = "generated by tonic-prost-build"
        )]
        tonic::include_proto!("vorpal.artifact");
    }

    /// `vorpal.context` service: the config-side context the agent queries.
    pub mod context {
        #![allow(
            clippy::all,
            clippy::pedantic,
            clippy::allow_attributes,
            clippy::allow_attributes_without_reason,
            clippy::clone_on_ref_ptr,
            missing_docs,
            reason = "generated by tonic-prost-build"
        )]
        tonic::include_proto!("vorpal.context");
    }

    /// `vorpal.worker` service: builds artifact steps on a worker.
    pub mod worker {
        #![allow(
            clippy::all,
            clippy::pedantic,
            clippy::allow_attributes,
            clippy::allow_attributes_without_reason,
            clippy::clone_on_ref_ptr,
            missing_docs,
            reason = "generated by tonic-prost-build"
        )]
        tonic::include_proto!("vorpal.worker");
    }
}

/// Artifact builders: the standard toolchain, language, and system
/// artifacts a config composes into its build graph.
pub mod artifact;
/// Command-line entry point that a config binary exposes to the `vorpal` CLI.
pub mod cli;
/// Config-side context: registers artifacts and talks to the agent.
pub mod context;
