[package]
edition = "2021"
name = "example"
version = "0.1.0"

[[bin]]
name = "vorpal"
path = "src/vorpal.rs"

[dependencies]
anyhow = "1"
tokio = { features = ["rt-multi-thread"], version = "1" }
vorpal-sdk = { git = "https://github.com/ALT-F4-LLC/vorpal.git", branch = "feature/update-sdks" }
