# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vorpal_sdk.api.worker import worker_pb2 as worker_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildArtifact = channel.unary_stream(
                '/vorpal.worker.WorkerService/BuildArtifact',
                request_serializer=worker_dot_worker__pb2.BuildArtifactRequest.SerializeToString,
                response_deserializer=worker_dot_worker__pb2.BuildArtifactResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def BuildArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildArtifact': grpc.unary_stream_rpc_method_handler(
                    servicer.BuildArtifact,
                    request_deserializer=worker_dot_worker__pb2.BuildArtifactRequest.FromString,
                    response_serializer=worker_dot_worker__pb2.BuildArtifactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vorpal.worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vorpal.worker.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuildArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vorpal.worker.WorkerService/BuildArtifact',
            worker_dot_worker__pb2.BuildArtifactRequest.SerializeToString,
            worker_dot_worker__pb2.BuildArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
