# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker/worker.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'worker/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vorpal_sdk.api.artifact import artifact_pb2 as artifact_dot_artifact__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13worker/worker.proto\x12\rvorpal.worker\x1a\x17\x61rtifact/artifact.proto\"\x8b\x01\n\x14\x42uildArtifactRequest\x12\x18\n\x10\x61rtifact_aliases\x18\x01 \x03(\t\x12\x1a\n\x12\x61rtifact_namespace\x18\x02 \x01(\t\x12\x10\n\x08registry\x18\x04 \x01(\t\x12+\n\x08\x61rtifact\x18\x03 \x01(\x0b\x32\x19.vorpal.artifact.Artifact\"\'\n\x15\x42uildArtifactResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2m\n\rWorkerService\x12\\\n\rBuildArtifact\x12#.vorpal.worker.BuildArtifactRequest\x1a$.vorpal.worker.BuildArtifactResponse0\x01\x42\x34Z2github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/workerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/worker'
  _globals['_BUILDARTIFACTREQUEST']._serialized_start=64
  _globals['_BUILDARTIFACTREQUEST']._serialized_end=203
  _globals['_BUILDARTIFACTRESPONSE']._serialized_start=205
  _globals['_BUILDARTIFACTRESPONSE']._serialized_end=244
  _globals['_WORKERSERVICE']._serialized_start=246
  _globals['_WORKERSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
