name: "Set up Vorpal"
description: "Downloads and sets up the Vorpal binary, and starts the service."
inputs:
  version:
    description: "The version of Vorpal to install (e.g., v0.1.0)."
    required: false
  use-local-build:
    description: "Use a pre-built binary from the workspace."
    required: false
    default: "false"
  registry-backend:
    description: "Registry backend to use (local, s3)."
    required: false
    default: "local"
  registry-backend-s3-bucket:
    description: "S3 bucket name for s3 backend."
    required: false
  port:
    description: "Port for vorpal services."
    required: false
    default: "23151"
  services:
    description: "Services to start (comma-separated)."
    required: false
    default: "agent,registry,worker"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/cleanup.js"
  post-if: "always()"
