[package]
edition = "2021"
name = "vorpal-example"
version = "0.1.0"

[[bin]]
name = "vorpal"
path = "vorpal.rs"

[dependencies]
anyhow = "1"
tokio = { version = "1" }
tokio-stream = "0"
vorpal = { path = "../../." }
