#!/usr/bin/env bash
set -euxo pipefail

apt-get remove --auto-remove --yes \
    wget

apt-get purge -y \
    --auto-remove \
    -o APT::AutoRemove::RecommendsImportant=false

apt-get clean

rm -rf /var/lib/apt/lists/*

rm -rf /tmp/*
