// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: context/context.proto

package context

import (
	artifact "github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/artifact"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_context_context_proto protoreflect.FileDescriptor

const file_context_context_proto_rawDesc = "" +
	"\n" +
	"\x15context/context.proto\x12\x0evorpal.context\x1a\x17artifact/artifact.proto2\xb3\x01\n" +
	"\x0eContextService\x12J\n" +
	"\vGetArtifact\x12 .vorpal.artifact.ArtifactRequest\x1a\x19.vorpal.artifact.Artifact\x12U\n" +
	"\fGetArtifacts\x12!.vorpal.artifact.ArtifactsRequest\x1a\".vorpal.artifact.ArtifactsResponseB5Z3github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/contextb\x06proto3"

var file_context_context_proto_goTypes = []any{
	(*artifact.ArtifactRequest)(nil),   // 0: vorpal.artifact.ArtifactRequest
	(*artifact.ArtifactsRequest)(nil),  // 1: vorpal.artifact.ArtifactsRequest
	(*artifact.Artifact)(nil),          // 2: vorpal.artifact.Artifact
	(*artifact.ArtifactsResponse)(nil), // 3: vorpal.artifact.ArtifactsResponse
}
var file_context_context_proto_depIdxs = []int32{
	0, // 0: vorpal.context.ContextService.GetArtifact:input_type -> vorpal.artifact.ArtifactRequest
	1, // 1: vorpal.context.ContextService.GetArtifacts:input_type -> vorpal.artifact.ArtifactsRequest
	2, // 2: vorpal.context.ContextService.GetArtifact:output_type -> vorpal.artifact.Artifact
	3, // 3: vorpal.context.ContextService.GetArtifacts:output_type -> vorpal.artifact.ArtifactsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_context_context_proto_init() }
func file_context_context_proto_init() {
	if File_context_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_context_proto_rawDesc), len(file_context_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_context_proto_goTypes,
		DependencyIndexes: file_context_context_proto_depIdxs,
	}.Build()
	File_context_context_proto = out.File
	file_context_context_proto_goTypes = nil
	file_context_context_proto_depIdxs = nil
}
