# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent/agent.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agent/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vorpal_sdk.api.artifact import artifact_pb2 as artifact_dot_artifact__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61gent/agent.proto\x12\x0cvorpal.agent\x1a\x17\x61rtifact/artifact.proto\"\xa6\x01\n\x16PrepareArtifactRequest\x12\x17\n\x0f\x61rtifact_unlock\x18\x01 \x01(\x08\x12\x18\n\x10\x61rtifact_context\x18\x02 \x01(\t\x12\x1a\n\x12\x61rtifact_namespace\x18\x03 \x01(\t\x12\x10\n\x08registry\x18\x04 \x01(\t\x12+\n\x08\x61rtifact\x18\x05 \x01(\x0b\x32\x19.vorpal.artifact.Artifact\"\xaa\x01\n\x17PrepareArtifactResponse\x12\x1c\n\x0f\x61rtifact_digest\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0f\x61rtifact_output\x18\x02 \x01(\tH\x01\x88\x01\x01\x12+\n\x08\x61rtifact\x18\x03 \x01(\x0b\x32\x19.vorpal.artifact.ArtifactB\x12\n\x10_artifact_digestB\x12\n\x10_artifact_output2r\n\x0c\x41gentService\x12\x62\n\x0fPrepareArtifact\x12$.vorpal.agent.PrepareArtifactRequest\x1a%.vorpal.agent.PrepareArtifactResponse\"\x00\x30\x01\x42\x33Z1github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/agentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/agent'
  _globals['_PREPAREARTIFACTREQUEST']._serialized_start=61
  _globals['_PREPAREARTIFACTREQUEST']._serialized_end=227
  _globals['_PREPAREARTIFACTRESPONSE']._serialized_start=230
  _globals['_PREPAREARTIFACTRESPONSE']._serialized_end=400
  _globals['_AGENTSERVICE']._serialized_start=402
  _globals['_AGENTSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
