# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vorpal_sdk.api.agent import agent_pb2 as agent_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareArtifact = channel.unary_stream(
                '/vorpal.agent.AgentService/PrepareArtifact',
                request_serializer=agent_dot_agent__pb2.PrepareArtifactRequest.SerializeToString,
                response_deserializer=agent_dot_agent__pb2.PrepareArtifactResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PrepareArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareArtifact': grpc.unary_stream_rpc_method_handler(
                    servicer.PrepareArtifact,
                    request_deserializer=agent_dot_agent__pb2.PrepareArtifactRequest.FromString,
                    response_serializer=agent_dot_agent__pb2.PrepareArtifactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vorpal.agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vorpal.agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vorpal.agent.AgentService/PrepareArtifact',
            agent_dot_agent__pb2.PrepareArtifactRequest.SerializeToString,
            agent_dot_agent__pb2.PrepareArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
