[package]
edition = "2021"
name = "example"
version = "0.1.0"

[[bin]]
name = "example"
path = "src/main.rs"

[[bin]]
name = "vorpal"
path = "src/vorpal.rs"

[dependencies]
anyhow = "1"
tokio = { features = ["rt-multi-thread"], version = "1" }
vorpal-sdk = "0.1.0-rc.1"
