# Code generated by linux-vorpal-codegen. DO NOT EDIT.

from __future__ import annotations

from typing import TYPE_CHECKING

from vorpal_sdk.artifact import Artifact
from vorpal_sdk.artifact.linux_debian import LinuxDebian
from vorpal_sdk.step import bwrap
from vorpal_sdk.artifact.linux_vorpal.scripts import (
    setup,
    stage_01,
    stage_02,
    stage_03,
    stage_04,
    stage_05,
)
from vorpal_sdk.artifact.linux_vorpal.source import (
    source_curl,
    source_curl_cacert,
    source_file,
    source_gnu,
    source_gnu_gcc,
    source_gnu_glibc_patch,
    source_gnu_xz,
    source_libidn2,
    source_libpsl,
    source_linux,
    source_ncurses,
    source_openssl,
    source_perl,
    source_python,
    source_unzip,
    source_unzip_patch_fixes,
    source_unzip_patch_gcc14,
    source_util_linux,
    source_xz,
    source_zlib,
)

if TYPE_CHECKING:
    from vorpal_sdk.context import ConfigContext


def linux_vorpal(context: ConfigContext) -> str:
    bash_version = "5.3"
    binutils_version = "2.45"
    bison_version = "3.8.2"
    coreutils_version = "9.7"
    curl_version = "8.15.0"
    curl_cacert_version = "1776122862"
    diffutils_version = "3.12"
    file_version = "5.46"
    findutils_version = "4.10.0"
    gawk_version = "5.3.2"
    gcc_version = "15.2.0"
    gettext_version = "0.26"
    glibc_version = "2.42"
    gmp_version = "6.3.0"
    grep_version = "3.12"
    gzip_version = "1.14"
    libidn2_version = "2.3.8"
    libpsl_version = "0.21.5"
    libunistring_version = "1.3"
    linux_version = "6.16.1"
    m4_version = "1.4.20"
    make_version = "4.4.1"
    mpc_version = "1.3.1"
    mpfr_version = "4.2.2"
    ncurses_version = "6.5-20250809"
    openssl_version = "3.5.2"
    patch_version = "2.8"
    perl_version = "5.42.0"
    python_version = "3.13.7"
    sed_version = "4.9"
    tar_version = "1.35"
    texinfo_version = "7.2"
    unzip_version = "6.0"
    util_linux_version = "2.41.1"
    xz_version = "5.8.1"
    zlib_version = "1.3.1"

    bash = source_gnu("bash", bash_version)
    binutils = source_gnu("binutils", binutils_version)
    bison = source_gnu("bison", bison_version)
    coreutils = source_gnu("coreutils", coreutils_version)
    curl = source_curl(curl_version)
    curl_cacert = source_curl_cacert(curl_cacert_version)
    diffutils = source_gnu_xz("diffutils", diffutils_version)
    file = source_file(file_version)
    findutils = source_gnu_xz("findutils", findutils_version)
    gawk = source_gnu("gawk", gawk_version)
    gcc = source_gnu_gcc(gcc_version)
    gettext = source_gnu("gettext", gettext_version)
    glibc = source_gnu("glibc", glibc_version)
    glibc_patch = source_gnu_glibc_patch(glibc_version)
    gmp = source_gnu("gmp", gmp_version)
    grep = source_gnu("grep", grep_version)
    gzip = source_gnu("gzip", gzip_version)
    libidn2 = source_libidn2(libidn2_version)
    libpsl = source_libpsl(libpsl_version)
    libunistring = source_gnu("libunistring", libunistring_version)
    linux = source_linux(linux_version)
    m4 = source_gnu("m4", m4_version)
    make = source_gnu("make", make_version)
    mpc = source_gnu("mpc", mpc_version)
    mpfr = source_gnu_xz("mpfr", mpfr_version)
    ncurses = source_ncurses(ncurses_version)
    openssl = source_openssl(openssl_version)
    patch = source_gnu("patch", patch_version)
    perl = source_perl(perl_version)
    python = source_python(python_version)
    sed = source_gnu("sed", sed_version)
    tar = source_gnu("tar", tar_version)
    texinfo = source_gnu("texinfo", texinfo_version)
    unzip = source_unzip(unzip_version)
    unzip_patch_fixes = source_unzip_patch_fixes("6.0")
    unzip_patch_gcc14 = source_unzip_patch_gcc14("6.0")
    util_linux = source_util_linux(util_linux_version)
    xz = source_xz(xz_version)
    zlib = source_zlib(zlib_version)

    step_environments = ["PATH=/usr/bin:/usr/sbin"]

    step_rootfs = LinuxDebian().build(context)

    step_setup_script = setup(
        binutils_version,
        gawk_version,
        gcc_version,
        glibc_version,
        gmp_version,
        mpc_version,
        mpfr_version,
        ncurses_version,
    )

    step_stage_01_script = stage_01(
        binutils_version,
        gcc_version,
        glibc_version,
        linux_version,
    )

    step_stage_02_script = stage_02(
        bash_version,
        binutils_version,
        coreutils_version,
        diffutils_version,
        file_version,
        findutils_version,
        gawk_version,
        gcc_version,
        grep_version,
        gzip_version,
        m4_version,
        make_version,
        ncurses_version,
        patch_version,
        sed_version,
        tar_version,
        xz_version,
    )

    step_stage_03_script = stage_03(
        bison_version,
        gettext_version,
        perl_version,
        python_version,
        texinfo_version,
        util_linux_version,
    )

    step_stage_04_script = stage_04(
        binutils_version,
        gcc_version,
        glibc_version,
        openssl_version,
        zlib_version,
    )

    step_stage_05_script = stage_05(
        curl_cacert_version,
        curl_version,
        libidn2_version,
        libpsl_version,
        libunistring_version,
        unzip_version,
    )

    bwrap_arguments = [
        "--bind",
        "$VORPAL_OUTPUT/bin",
        "/bin",
        "--bind",
        "$VORPAL_OUTPUT/etc",
        "/etc",
        "--bind",
        "$VORPAL_OUTPUT/lib",
        "/lib",
        "--bind-try",
        "$VORPAL_OUTPUT/lib64",
        "/lib64",
        "--bind",
        "$VORPAL_OUTPUT/sbin",
        "/sbin",
        "--bind",
        "$VORPAL_OUTPUT/usr",
        "/usr",
        "--bind",
        "$VORPAL_WORKSPACE",
        "$VORPAL_WORKSPACE",
        "--chdir",
        "$VORPAL_WORKSPACE",
        "--gid",
        "0",
        "--uid",
        "0",
    ]

    systems = ["aarch64-linux", "x86_64-linux"]

    steps = [
        bwrap(
            [],
            [],
            list(step_environments),
            step_rootfs,
            [],
            step_setup_script,
        ),
        bwrap(
            [],
            [],
            list(step_environments),
            step_rootfs,
            [],
            step_stage_01_script,
        ),
        bwrap(
            [],
            [],
            list(step_environments),
            step_rootfs,
            [],
            step_stage_02_script,
        ),
        bwrap(
            [*bwrap_arguments, "--bind", "$VORPAL_OUTPUT/tools", "/tools"],
            [],
            list(step_environments),
            None,
            [],
            step_stage_03_script,
        ),
        bwrap(
            [],
            [],
            list(step_environments),
            step_rootfs,
            [],
            "rm -rf $VORPAL_OUTPUT/tools",
        ),
        bwrap(
            bwrap_arguments,
            [],
            list(step_environments),
            None,
            [],
            step_stage_04_script,
        ),
        bwrap(
            bwrap_arguments,
            [],
            list(step_environments),
            None,
            [],
            step_stage_05_script,
        ),
    ]

    sources = [
        bash,
        binutils,
        bison,
        coreutils,
        curl,
        curl_cacert,
        diffutils,
        file,
        findutils,
        gawk,
        gcc,
        gettext,
        glibc,
        glibc_patch,
        gmp,
        grep,
        gzip,
        libidn2,
        libpsl,
        libunistring,
        linux,
        m4,
        make,
        mpc,
        mpfr,
        ncurses,
        openssl,
        patch,
        perl,
        python,
        sed,
        tar,
        texinfo,
        unzip,
        unzip_patch_fixes,
        unzip_patch_gcc14,
        util_linux,
        xz,
        zlib,
    ]

    name = "linux-vorpal"

    return (
        Artifact(name, steps, systems)
        .with_aliases([f"{name}:latest"])
        .with_sources(sources)
        .build(context)
    )
