# Code generated by linux-vorpal-codegen. DO NOT EDIT.

from __future__ import annotations

from vorpal_sdk.api.artifact import artifact_pb2
from vorpal_sdk.artifact import ArtifactSource

def source_curl(version: str) -> artifact_pb2.ArtifactSource:
    name = "curl"
    path = f"https://sdk.vorpal.build/source/{name}-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_curl_cacert(version: str) -> artifact_pb2.ArtifactSource:
    name = "curl-cacert"
    path = f"https://sdk.vorpal.build/source/cacert-{version}.pem"

    return ArtifactSource(name, path).build()

def source_file(version: str) -> artifact_pb2.ArtifactSource:
    name = "file"
    path = f"https://sdk.vorpal.build/source/file-{version}.tar.gz"

    return ArtifactSource(name, path).build()

def source_gnu(name: str, version: str) -> artifact_pb2.ArtifactSource:
    path = f"https://sdk.vorpal.build/source/{name}-{version}.tar.gz"

    return ArtifactSource(name, path).build()

def source_gnu_xz(name: str, version: str) -> artifact_pb2.ArtifactSource:
    path = f"https://sdk.vorpal.build/source/{name}-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_gnu_gcc(version: str) -> artifact_pb2.ArtifactSource:
    name = "gcc"
    path = f"https://sdk.vorpal.build/source/gcc-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_gnu_glibc_patch(version: str) -> artifact_pb2.ArtifactSource:
    name = "glibc-patch"
    path = f"https://sdk.vorpal.build/source/glibc-{version}-fhs-1.patch"

    return ArtifactSource(name, path).build()

def source_libidn2(version: str) -> artifact_pb2.ArtifactSource:
    name = "libidn2"
    path = f"https://sdk.vorpal.build/source/libidn2-{version}.tar.gz"

    return ArtifactSource(name, path).build()

def source_libpsl(version: str) -> artifact_pb2.ArtifactSource:
    name = "libpsl"
    path = f"https://sdk.vorpal.build/source/libpsl-{version}.tar.gz"

    return ArtifactSource(name, path).build()

def source_linux(version: str) -> artifact_pb2.ArtifactSource:
    name = "linux"
    path = f"https://sdk.vorpal.build/source/linux-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_ncurses(version: str) -> artifact_pb2.ArtifactSource:
    name = "ncurses"
    path = f"https://sdk.vorpal.build/source/ncurses-{version}.tar.gz"

    return ArtifactSource(name, path).build()

def source_openssl(version: str) -> artifact_pb2.ArtifactSource:
    name = "openssl"
    path = f"https://sdk.vorpal.build/source/openssl-{version}.tar.gz"

    return ArtifactSource(name, path).build()

def source_perl(version: str) -> artifact_pb2.ArtifactSource:
    name = "perl"
    path = f"https://sdk.vorpal.build/source/perl-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_python(version: str) -> artifact_pb2.ArtifactSource:
    name = "python"
    path = f"https://sdk.vorpal.build/source/Python-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_unzip_patch_fixes(version: str) -> artifact_pb2.ArtifactSource:
    name = "unzip-patch-fixes"
    path = f"https://sdk.vorpal.build/source/unzip-{version}-consolidated_fixes-1.patch"

    return ArtifactSource(name, path).build()

def source_unzip_patch_gcc14(version: str) -> artifact_pb2.ArtifactSource:
    name = "unzip-patch-gcc14"
    path = f"https://sdk.vorpal.build/source/unzip-{version}-gcc14-1.patch"

    return ArtifactSource(name, path).build()

def source_unzip(version: str) -> artifact_pb2.ArtifactSource:
    name = "unzip"
    version_clean = version.replace(".", "")
    path = f"https://sdk.vorpal.build/source/unzip{version_clean}.tar.gz"

    return ArtifactSource(name, path).build()

def source_util_linux(version: str) -> artifact_pb2.ArtifactSource:
    name = "util-linux"
    path = f"https://sdk.vorpal.build/source/util-linux-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_xz(version: str) -> artifact_pb2.ArtifactSource:
    name = "xz"
    path = f"https://sdk.vorpal.build/source/xz-{version}.tar.xz"

    return ArtifactSource(name, path).build()

def source_zlib(version: str) -> artifact_pb2.ArtifactSource:
    name = "zlib"
    path = f"https://sdk.vorpal.build/source/zlib-{version}.tar.gz"

    return ArtifactSource(name, path).build()
