// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: agent/agent.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type handleServerStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Artifact } from "../artifact/artifact.js";

export const protobufPackage = "vorpal.agent";

export interface PrepareArtifactRequest {
  artifact_unlock: boolean;
  artifact_context: string;
  artifact_namespace: string;
  registry: string;
  artifact?: Artifact | undefined;
}

export interface PrepareArtifactResponse {
  artifact_digest?: string | undefined;
  artifact_output?: string | undefined;
  artifact?: Artifact | undefined;
}

function createBasePrepareArtifactRequest(): PrepareArtifactRequest {
  return { artifact_unlock: false, artifact_context: "", artifact_namespace: "", registry: "", artifact: undefined };
}

export const PrepareArtifactRequest: MessageFns<PrepareArtifactRequest> = {
  encode(message: PrepareArtifactRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.artifact_unlock !== false) {
      writer.uint32(8).bool(message.artifact_unlock);
    }
    if (message.artifact_context !== "") {
      writer.uint32(18).string(message.artifact_context);
    }
    if (message.artifact_namespace !== "") {
      writer.uint32(26).string(message.artifact_namespace);
    }
    if (message.registry !== "") {
      writer.uint32(34).string(message.registry);
    }
    if (message.artifact !== undefined) {
      Artifact.encode(message.artifact, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PrepareArtifactRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePrepareArtifactRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.artifact_unlock = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.artifact_context = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.artifact_namespace = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.registry = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.artifact = Artifact.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PrepareArtifactRequest {
    return {
      artifact_unlock: isSet(object.artifactUnlock)
        ? globalThis.Boolean(object.artifactUnlock)
        : isSet(object.artifact_unlock)
        ? globalThis.Boolean(object.artifact_unlock)
        : false,
      artifact_context: isSet(object.artifactContext)
        ? globalThis.String(object.artifactContext)
        : isSet(object.artifact_context)
        ? globalThis.String(object.artifact_context)
        : "",
      artifact_namespace: isSet(object.artifactNamespace)
        ? globalThis.String(object.artifactNamespace)
        : isSet(object.artifact_namespace)
        ? globalThis.String(object.artifact_namespace)
        : "",
      registry: isSet(object.registry) ? globalThis.String(object.registry) : "",
      artifact: isSet(object.artifact) ? Artifact.fromJSON(object.artifact) : undefined,
    };
  },

  toJSON(message: PrepareArtifactRequest): unknown {
    const obj: any = {};
    if (message.artifact_unlock !== false) {
      obj.artifactUnlock = message.artifact_unlock;
    }
    if (message.artifact_context !== "") {
      obj.artifactContext = message.artifact_context;
    }
    if (message.artifact_namespace !== "") {
      obj.artifactNamespace = message.artifact_namespace;
    }
    if (message.registry !== "") {
      obj.registry = message.registry;
    }
    if (message.artifact !== undefined) {
      obj.artifact = Artifact.toJSON(message.artifact);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PrepareArtifactRequest>, I>>(base?: I): PrepareArtifactRequest {
    return PrepareArtifactRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PrepareArtifactRequest>, I>>(object: I): PrepareArtifactRequest {
    const message = createBasePrepareArtifactRequest();
    message.artifact_unlock = object.artifact_unlock ?? false;
    message.artifact_context = object.artifact_context ?? "";
    message.artifact_namespace = object.artifact_namespace ?? "";
    message.registry = object.registry ?? "";
    message.artifact = (object.artifact !== undefined && object.artifact !== null)
      ? Artifact.fromPartial(object.artifact)
      : undefined;
    return message;
  },
};

function createBasePrepareArtifactResponse(): PrepareArtifactResponse {
  return { artifact_digest: undefined, artifact_output: undefined, artifact: undefined };
}

export const PrepareArtifactResponse: MessageFns<PrepareArtifactResponse> = {
  encode(message: PrepareArtifactResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.artifact_digest !== undefined) {
      writer.uint32(10).string(message.artifact_digest);
    }
    if (message.artifact_output !== undefined) {
      writer.uint32(18).string(message.artifact_output);
    }
    if (message.artifact !== undefined) {
      Artifact.encode(message.artifact, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PrepareArtifactResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePrepareArtifactResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.artifact_digest = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.artifact_output = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.artifact = Artifact.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PrepareArtifactResponse {
    return {
      artifact_digest: isSet(object.artifactDigest)
        ? globalThis.String(object.artifactDigest)
        : isSet(object.artifact_digest)
        ? globalThis.String(object.artifact_digest)
        : undefined,
      artifact_output: isSet(object.artifactOutput)
        ? globalThis.String(object.artifactOutput)
        : isSet(object.artifact_output)
        ? globalThis.String(object.artifact_output)
        : undefined,
      artifact: isSet(object.artifact) ? Artifact.fromJSON(object.artifact) : undefined,
    };
  },

  toJSON(message: PrepareArtifactResponse): unknown {
    const obj: any = {};
    if (message.artifact_digest !== undefined) {
      obj.artifactDigest = message.artifact_digest;
    }
    if (message.artifact_output !== undefined) {
      obj.artifactOutput = message.artifact_output;
    }
    if (message.artifact !== undefined) {
      obj.artifact = Artifact.toJSON(message.artifact);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PrepareArtifactResponse>, I>>(base?: I): PrepareArtifactResponse {
    return PrepareArtifactResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PrepareArtifactResponse>, I>>(object: I): PrepareArtifactResponse {
    const message = createBasePrepareArtifactResponse();
    message.artifact_digest = object.artifact_digest ?? undefined;
    message.artifact_output = object.artifact_output ?? undefined;
    message.artifact = (object.artifact !== undefined && object.artifact !== null)
      ? Artifact.fromPartial(object.artifact)
      : undefined;
    return message;
  },
};

export type AgentServiceService = typeof AgentServiceService;
export const AgentServiceService = {
  prepareArtifact: {
    path: "/vorpal.agent.AgentService/PrepareArtifact" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: PrepareArtifactRequest): Buffer =>
      Buffer.from(PrepareArtifactRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PrepareArtifactRequest => PrepareArtifactRequest.decode(value),
    responseSerialize: (value: PrepareArtifactResponse): Buffer =>
      Buffer.from(PrepareArtifactResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PrepareArtifactResponse => PrepareArtifactResponse.decode(value),
  },
} as const;

export interface AgentServiceServer extends UntypedServiceImplementation {
  prepareArtifact: handleServerStreamingCall<PrepareArtifactRequest, PrepareArtifactResponse>;
}

export interface AgentServiceClient extends Client {
  prepareArtifact(
    request: PrepareArtifactRequest,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<PrepareArtifactResponse>;
  prepareArtifact(
    request: PrepareArtifactRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<PrepareArtifactResponse>;
}

export const AgentServiceClient = makeGenericClientConstructor(
  AgentServiceService,
  "vorpal.agent.AgentService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AgentServiceClient;
  service: typeof AgentServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
