// Code generated by linux-vorpal-codegen. DO NOT EDIT.

package artifact

import (
	api "github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/artifact"
	"github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/config"
)

func linuxVorpalBuild(ctx *config.ConfigContext) (*string, error) {
	bashVersion := "5.3"
	binutilsVersion := "2.45"
	bisonVersion := "3.8.2"
	coreutilsVersion := "9.7"
	curlVersion := "8.15.0"
	curlCacertVersion := "1776122862"
	diffutilsVersion := "3.12"
	fileVersion := "5.46"
	findutilsVersion := "4.10.0"
	gawkVersion := "5.3.2"
	gccVersion := "15.2.0"
	gettextVersion := "0.26"
	glibcVersion := "2.42"
	gmpVersion := "6.3.0"
	grepVersion := "3.12"
	gzipVersion := "1.14"
	libidn2Version := "2.3.8"
	libpslVersion := "0.21.5"
	libunistringVersion := "1.3"
	linuxVersion := "6.16.1"
	m4Version := "1.4.20"
	makeVersion := "4.4.1"
	mpcVersion := "1.3.1"
	mpfrVersion := "4.2.2"
	ncursesVersion := "6.5-20250809"
	opensslVersion := "3.5.2"
	patchVersion := "2.8"
	perlVersion := "5.42.0"
	pythonVersion := "3.13.7"
	sedVersion := "4.9"
	tarVersion := "1.35"
	texinfoVersion := "7.2"
	unzipVersion := "6.0"
	utilLinuxVersion := "2.41.1"
	xzVersion := "5.8.1"
	zlibVersion := "1.3.1"

	bash := linuxVorpalSourceGnu("bash", bashVersion)
	binutils := linuxVorpalSourceGnu("binutils", binutilsVersion)
	bison := linuxVorpalSourceGnu("bison", bisonVersion)
	coreutils := linuxVorpalSourceGnu("coreutils", coreutilsVersion)
	curl := linuxVorpalSourceCurl(curlVersion)
	curlCacert := linuxVorpalSourceCurlCacert(curlCacertVersion)
	diffutils := linuxVorpalSourceGnuXz("diffutils", diffutilsVersion)
	file := linuxVorpalSourceFile(fileVersion)
	findutils := linuxVorpalSourceGnuXz("findutils", findutilsVersion)
	gawk := linuxVorpalSourceGnu("gawk", gawkVersion)
	gcc := linuxVorpalSourceGnuGcc(gccVersion)
	gettext := linuxVorpalSourceGnu("gettext", gettextVersion)
	glibc := linuxVorpalSourceGnu("glibc", glibcVersion)
	glibcPatch := linuxVorpalSourceGnuGlibcPatch(glibcVersion)
	gmp := linuxVorpalSourceGnu("gmp", gmpVersion)
	grep := linuxVorpalSourceGnu("grep", grepVersion)
	gzip := linuxVorpalSourceGnu("gzip", gzipVersion)
	libidn2 := linuxVorpalSourceLibidn2(libidn2Version)
	libpsl := linuxVorpalSourceLibpsl(libpslVersion)
	libunistring := linuxVorpalSourceGnu("libunistring", libunistringVersion)
	linux := linuxVorpalSourceLinux(linuxVersion)
	m4 := linuxVorpalSourceGnu("m4", m4Version)
	makeSrc := linuxVorpalSourceGnu("make", makeVersion)
	mpc := linuxVorpalSourceGnu("mpc", mpcVersion)
	mpfr := linuxVorpalSourceGnuXz("mpfr", mpfrVersion)
	ncurses := linuxVorpalSourceNcurses(ncursesVersion)
	openssl := linuxVorpalSourceOpenssl(opensslVersion)
	patch := linuxVorpalSourceGnu("patch", patchVersion)
	perl := linuxVorpalSourcePerl(perlVersion)
	python := linuxVorpalSourcePython(pythonVersion)
	sed := linuxVorpalSourceGnu("sed", sedVersion)
	tar := linuxVorpalSourceGnu("tar", tarVersion)
	texinfo := linuxVorpalSourceGnu("texinfo", texinfoVersion)
	unzip := linuxVorpalSourceUnzip(unzipVersion)
	unzipPatchFixes := linuxVorpalSourceUnzipPatchFixes("6.0")
	unzipPatchGcc14 := linuxVorpalSourceUnzipPatchGcc14("6.0")
	utilLinux := linuxVorpalSourceUtilLinux(utilLinuxVersion)
	xz := linuxVorpalSourceXz(xzVersion)
	zlib := linuxVorpalSourceZlib(zlibVersion)

	stepEnvironments := []string{"PATH=/usr/bin:/usr/sbin"}

	stepRootfs, err := NewLinuxDebian().Build(ctx)
	if err != nil {
		return nil, err
	}

	stepSetupScript := linuxVorpalSetup(
		binutilsVersion,
		gawkVersion,
		gccVersion,
		glibcVersion,
		gmpVersion,
		mpcVersion,
		mpfrVersion,
		ncursesVersion,
	)

	stepStage01Script := linuxVorpalStage01(
		binutilsVersion,
		gccVersion,
		glibcVersion,
		linuxVersion,
	)

	stepStage02Script := linuxVorpalStage02(
		bashVersion,
		binutilsVersion,
		coreutilsVersion,
		diffutilsVersion,
		fileVersion,
		findutilsVersion,
		gawkVersion,
		gccVersion,
		grepVersion,
		gzipVersion,
		m4Version,
		makeVersion,
		ncursesVersion,
		patchVersion,
		sedVersion,
		tarVersion,
		xzVersion,
	)

	stepStage03Script := linuxVorpalStage03(
		bisonVersion,
		gettextVersion,
		perlVersion,
		pythonVersion,
		texinfoVersion,
		utilLinuxVersion,
	)

	stepStage04Script := linuxVorpalStage04(
		binutilsVersion,
		gccVersion,
		glibcVersion,
		opensslVersion,
		zlibVersion,
	)

	stepStage05Script := linuxVorpalStage05(
		curlVersion,
		libidn2Version,
		libpslVersion,
		libunistringVersion,
		unzipVersion,
	)

	bwrapArguments := []string{
		// mount bin
		"--bind",
		"$VORPAL_OUTPUT/bin",
		"/bin",
		// mount etc
		"--bind",
		"$VORPAL_OUTPUT/etc",
		"/etc",
		// mount lib
		"--bind",
		"$VORPAL_OUTPUT/lib",
		"/lib",
		// mount lib64 (if exists)
		"--bind-try",
		"$VORPAL_OUTPUT/lib64",
		"/lib64",
		// mount sbin
		"--bind",
		"$VORPAL_OUTPUT/sbin",
		"/sbin",
		// mount usr
		"--bind",
		"$VORPAL_OUTPUT/usr",
		"/usr",
		// mount current directory
		"--bind",
		"$VORPAL_WORKSPACE",
		"$VORPAL_WORKSPACE",
		// change directory
		"--chdir",
		"$VORPAL_WORKSPACE",
		// set group id
		"--gid",
		"0",
		// set user id
		"--uid",
		"0",
	}

	systems := []api.ArtifactSystem{api.ArtifactSystem_AARCH64_LINUX, api.ArtifactSystem_X8664_LINUX}

	steps := make([]*api.ArtifactStep, 0)

	step0, err := Bwrap(
		[]string{},
		[]*string{},
		stepEnvironments,
		stepRootfs,
		stepSetupScript,
		[]*api.ArtifactStepSecret{},
	)
	if err != nil {
		return nil, err
	}
	steps = append(steps, step0)

	step1, err := Bwrap(
		[]string{},
		[]*string{},
		stepEnvironments,
		stepRootfs,
		stepStage01Script,
		[]*api.ArtifactStepSecret{},
	)
	if err != nil {
		return nil, err
	}
	steps = append(steps, step1)

	step2, err := Bwrap(
		[]string{},
		[]*string{},
		stepEnvironments,
		stepRootfs,
		stepStage02Script,
		[]*api.ArtifactStepSecret{},
	)
	if err != nil {
		return nil, err
	}
	steps = append(steps, step2)

	step3, err := Bwrap(
		append(append([]string{}, bwrapArguments...), "--bind", "$VORPAL_OUTPUT/tools", "/tools"),
		[]*string{},
		stepEnvironments,
		nil,
		stepStage03Script,
		[]*api.ArtifactStepSecret{},
	)
	if err != nil {
		return nil, err
	}
	steps = append(steps, step3)

	step4, err := Bwrap(
		[]string{},
		[]*string{},
		stepEnvironments,
		stepRootfs,
		"rm -rf $VORPAL_OUTPUT/tools",
		[]*api.ArtifactStepSecret{},
	)
	if err != nil {
		return nil, err
	}
	steps = append(steps, step4)

	step5, err := Bwrap(
		bwrapArguments,
		[]*string{},
		stepEnvironments,
		nil,
		stepStage04Script,
		[]*api.ArtifactStepSecret{},
	)
	if err != nil {
		return nil, err
	}
	steps = append(steps, step5)

	step6, err := Bwrap(
		bwrapArguments,
		[]*string{},
		stepEnvironments,
		nil,
		stepStage05Script,
		[]*api.ArtifactStepSecret{},
	)
	if err != nil {
		return nil, err
	}
	steps = append(steps, step6)

	sources := []*api.ArtifactSource{
		&bash,
		&binutils,
		&bison,
		&coreutils,
		&curl,
		&curlCacert,
		&diffutils,
		&file,
		&findutils,
		&gawk,
		&gcc,
		&gettext,
		&glibc,
		&glibcPatch,
		&gmp,
		&grep,
		&gzip,
		&libidn2,
		&libpsl,
		&libunistring,
		&linux,
		&m4,
		&makeSrc,
		&mpc,
		&mpfr,
		&ncurses,
		&openssl,
		&patch,
		&perl,
		&python,
		&sed,
		&tar,
		&texinfo,
		&unzip,
		&unzipPatchFixes,
		&unzipPatchGcc14,
		&utilLinux,
		&xz,
		&zlib,
	}

	name := "linux-vorpal"

	return NewArtifact(name, steps, systems).
		WithAliases([]string{name + ":latest"}).
		WithSources(sources).
		Build(ctx)
}
