// Code generated by linux-vorpal-codegen. DO NOT EDIT.

package artifact

import "fmt"

func linuxVorpalStage02(bashVersion string, binutilsVersion string, coreutilsVersion string, diffutilsVersion string, fileVersion string, findutilsVersion string, gawkVersion string, gccVersion string, grepVersion string, gzipVersion string, m4Version string, makeVersion string, ncursesVersion string, patchVersion string, sedVersion string, tarVersion string, xzVersion string) string {
	return fmt.Sprintf(`set +h
umask 022

## Setup environment

export LC_ALL="POSIX"
export VORPAL_TARGET="$(uname -m)-vorpal-linux-gnu"
export PATH="$VORPAL_OUTPUT/tools/bin:$PATH"
export CONFIG_SITE="$VORPAL_OUTPUT/usr/share/config.site"
export MAKEFLAGS="-j$(nproc)"
export VORPAL_SOURCE="$(pwd)/source"

## Build m4

mkdir -p $VORPAL_SOURCE/m4/m4-%s/build
pushd $VORPAL_SOURCE/m4/m4-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/m4

## Build ncurses

mkdir -p $VORPAL_SOURCE/ncurses/ncurses-%s
pushd $VORPAL_SOURCE/ncurses/ncurses-%s

mkdir -p build
pushd build

../configure --prefix=$VORPAL_OUTPUT/tools AWK=gawk

make -C include
make -C progs tic
install progs/tic $VORPAL_OUTPUT/tools/bin

popd

./configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(./config.guess)" --mandir="/usr/share/man" --with-manpage-format="normal" --with-shared --without-normal --with-cxx-shared --without-debug --without-ada --disable-stripping AWK=gawk

make
make DESTDIR="$VORPAL_OUTPUT" TIC_PATH="$(pwd)/build/progs/tic" install

ln -s libncursesw.so $VORPAL_OUTPUT/usr/lib/libncurses.so

sed -e 's/^#if.*XOPEN.*$/#if 1/' -i $VORPAL_OUTPUT/usr/include/curses.h

popd

rm -rf $VORPAL_SOURCE/ncurses

## Build bash

mkdir -p $VORPAL_SOURCE/bash/bash-%s/build
pushd $VORPAL_SOURCE/bash/bash-%s/build

../configure --prefix="/usr" --build="$(sh ../support/config.guess)" --host="$VORPAL_TARGET" --without-bash-malloc

make
make DESTDIR="$VORPAL_OUTPUT" install

ln -s bash $VORPAL_OUTPUT/usr/bin/sh

popd

rm -rf $VORPAL_SOURCE/bash

## Build coreutils

mkdir -p $VORPAL_SOURCE/coreutils/coreutils-%s/build
pushd $VORPAL_SOURCE/coreutils/coreutils-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)" --enable-install-program="hostname" --enable-no-install-program="kill,uptime"

make
make DESTDIR="$VORPAL_OUTPUT" install

mv $VORPAL_OUTPUT/usr/bin/chroot $VORPAL_OUTPUT/usr/sbin

mkdir -p $VORPAL_OUTPUT/usr/share/man/man8

mv $VORPAL_OUTPUT/usr/share/man/man1/chroot.1 $VORPAL_OUTPUT/usr/share/man/man8/chroot.8

sed -i 's/"1"/"8"/' $VORPAL_OUTPUT/usr/share/man/man8/chroot.8

popd

rm -rf $VORPAL_SOURCE/coreutils

## Build diffutils

mkdir -p $VORPAL_SOURCE/diffutils/diffutils-%s/build
pushd $VORPAL_SOURCE/diffutils/diffutils-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" gl_cv_func_strcasecmp_works=y --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/diffutils

## Build file

mkdir -p $VORPAL_SOURCE/file/file-%s
pushd $VORPAL_SOURCE/file/file-%s

mkdir -p build
pushd build

../configure --disable-bzlib --disable-libseccomp --disable-xzlib --disable-zlib

make

popd

./configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(./config.guess)"

make FILE_COMPILE="$(pwd)/build/src/file"
make DESTDIR="$VORPAL_OUTPUT" install

rm $VORPAL_OUTPUT/usr/lib/libmagic.la

popd

rm -rf $VORPAL_SOURCE/file

## Build findutils

mkdir -p $VORPAL_SOURCE/findutils/findutils-%s/build
pushd $VORPAL_SOURCE/findutils/findutils-%s/build

../configure --prefix="/usr" --localstatedir="/var/lib/locate" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/findutils

## Build gawk

mkdir -p $VORPAL_SOURCE/gawk/gawk-%s/build
pushd $VORPAL_SOURCE/gawk/gawk-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/gawk

## Build grep

mkdir -p $VORPAL_SOURCE/grep/grep-%s/build
pushd $VORPAL_SOURCE/grep/grep-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/grep

## Build gzip

mkdir -p $VORPAL_SOURCE/gzip/gzip-%s/build
pushd $VORPAL_SOURCE/gzip/gzip-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/gzip

## Build make

mkdir -p $VORPAL_SOURCE/make/make-%s/build
pushd $VORPAL_SOURCE/make/make-%s/build

../configure --prefix="/usr" --without-guile --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/make

## Build patch

mkdir -p $VORPAL_SOURCE/patch/patch-%s/build
pushd $VORPAL_SOURCE/patch/patch-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/patch

## Build sed

mkdir -p $VORPAL_SOURCE/sed/sed-%s/build
pushd $VORPAL_SOURCE/sed/sed-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/sed

## Build tar

mkdir -p $VORPAL_SOURCE/tar/tar-%s/build
pushd $VORPAL_SOURCE/tar/tar-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$($VORPAL_SOURCE/tar/tar-%s/build-aux/config.guess)"

make
make DESTDIR="$VORPAL_OUTPUT" install

popd

rm -rf $VORPAL_SOURCE/tar

## Build xz

mkdir -p $VORPAL_SOURCE/xz/xz-%s/build
pushd $VORPAL_SOURCE/xz/xz-%s/build

../configure --prefix="/usr" --host="$VORPAL_TARGET" --build="$(../build-aux/config.guess)" --disable-static --docdir="/usr/share/doc/xz-5.6.3"

make
make DESTDIR="$VORPAL_OUTPUT" install

rm $VORPAL_OUTPUT/usr/lib/liblzma.la

popd

rm -rf $VORPAL_SOURCE/xz

## Build binutils (pass 02)

mkdir -p $VORPAL_SOURCE/binutils-pass-02/binutils-%s/build
pushd $VORPAL_SOURCE/binutils-pass-02/binutils-%s/build

../configure --prefix="/usr" --build="$(../config.guess)" --host="$VORPAL_TARGET" --disable-nls --enable-shared --enable-gprofng="no" --disable-werror --enable-64-bit-bfd --enable-new-dtags --enable-default-hash-style="gnu"

make
make DESTDIR="$VORPAL_OUTPUT" install

rm $VORPAL_OUTPUT/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes,sframe}.{a,la}

popd

rm -rf $VORPAL_SOURCE/binutils-pass-02

## Build gcc (pass 02)

mkdir -p $VORPAL_SOURCE/gcc-pass-02/gcc-%s/build
pushd $VORPAL_SOURCE/gcc-pass-02/gcc-%s/build

../configure --build="$(../config.guess)" --host="$VORPAL_TARGET" --target="$VORPAL_TARGET" LDFLAGS_FOR_TARGET="-L$PWD/$VORPAL_TARGET/libgcc" --prefix="/usr" --with-build-sysroot="$VORPAL_OUTPUT" --enable-default-pie --enable-default-ssp --disable-nls --disable-multilib --disable-libatomic --disable-libgomp --disable-libquadmath --disable-libsanitizer --disable-libssp --disable-libvtv --enable-languages="c,c++"

make
make DESTDIR="$VORPAL_OUTPUT" install

ln -s gcc $VORPAL_OUTPUT/usr/bin/cc

popd

rm -rf $VORPAL_SOURCE/gcc-pass-02

## Setup root symlinks

ln -sf usr/bin $VORPAL_OUTPUT/bin
ln -sf usr/lib $VORPAL_OUTPUT/lib
ln -sf usr/sbin $VORPAL_OUTPUT/sbin`, m4Version, m4Version, ncursesVersion, ncursesVersion, bashVersion, bashVersion, coreutilsVersion, coreutilsVersion, diffutilsVersion, diffutilsVersion, fileVersion, fileVersion, findutilsVersion, findutilsVersion, gawkVersion, gawkVersion, grepVersion, grepVersion, gzipVersion, gzipVersion, makeVersion, makeVersion, patchVersion, patchVersion, sedVersion, sedVersion, tarVersion, tarVersion, tarVersion, xzVersion, xzVersion, binutilsVersion, binutilsVersion, gccVersion, gccVersion)
}
