# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: context/context.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'context/context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vorpal_sdk.api.artifact import artifact_pb2 as artifact_dot_artifact__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontext/context.proto\x12\x0evorpal.context\x1a\x17\x61rtifact/artifact.proto2\xb3\x01\n\x0e\x43ontextService\x12J\n\x0bGetArtifact\x12 .vorpal.artifact.ArtifactRequest\x1a\x19.vorpal.artifact.Artifact\x12U\n\x0cGetArtifacts\x12!.vorpal.artifact.ArtifactsRequest\x1a\".vorpal.artifact.ArtifactsResponseB5Z3github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/contextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context.context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/ALT-F4-LLC/vorpal/sdk/go/pkg/api/context'
  _globals['_CONTEXTSERVICE']._serialized_start=67
  _globals['_CONTEXTSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
