name: dev

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ./dev.sh just format

      - run: ./dev.sh just lint

      - run: ./dev.sh just check

      - run: ./dev.sh just test

      - run: ./dev.sh just build
